-- Soft per-person kill-switch for the employee app. Each install registers a device id and checks in
-- on launch; the owner can flip `revoked` on any one device to lock just that person's app without
-- resetting everyone. (Soft: the shared key is still in the APK, so this stops a cooperating person,
-- not a determined one who extracts the key — acceptable for trusted staff. See docs.)

CREATE TABLE IF NOT EXISTS app_device (
    id UUID PRIMARY KEY,                          -- generated by the app, persisted in its prefs
    channel TEXT NOT NULL DEFAULT 'employee',
    label TEXT,                                   -- device model, or a name the owner sets
    revoked BOOLEAN NOT NULL DEFAULT FALSE,
    app_version TEXT,
    first_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_app_device_channel ON app_device (channel, last_seen_at DESC);
