"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";

import { isGamePath } from "@/lib/marketplace/game-paths.js";
import { useEffect, useState } from "react";
import { FaDharmachakra } from "react-icons/fa6";

import FishingLaunch from "@/components/FishingLaunch";
import MiningLaunch from "@/components/MiningLaunch";
import DungeonLaunch from "@/components/DungeonLaunch";
import SurveyModal from "@/components/SurveyModal";
import AnnouncementModal from "@/components/AnnouncementModal";
import ForgeAnnounce from "@/components/ForgeAnnounce";
import { useItemSprite } from "@/components/ItemArt";
import useScrollLock from "@/lib/useScrollLock";

// The Sets menu icon: the die-cut Warplate Helm sprite (falls back to a helmet emoji until it loads) — a real
// piece of gear reads far better here than the old puzzle-piece glyph.
function SetsHelmet({ size = 18 }) {
    const sprite = useItemSprite("warplate_helm");
    if (sprite) return <img src={sprite} alt="" width={size} height={size} style={{ width: size, height: size, objectFit: "contain", verticalAlign: "-0.28em" }} />;
    return <span aria-hidden="true">🪖</span>;
}
// Menu destination → its die-cut sprite in /public/images/nav (generated by scripts/gen-nav-icons.mjs).
// Keyed by href so the strip and the grid both pick it up without duplicating a field on 40-odd entries.
// Emoji belong to Apple and Google, render differently on every device, and looked borrowed sitting next to
// the game's own art. /marketplace/sets is deliberately missing — it uses the real Warplate Helm item sprite.
const NAV_SPRITE = {
    "/marketplace/town": "town", "/marketplace/boss": "boss", "/marketplace/sailing": "sailing",
    "/marketplace/farm": "farm", "/marketplace/spin": "spin", "/marketplace/quests": "quests",
    "/marketplace/bounties": "bounties", "/marketplace/inventory": "gear", "/marketplace/pets": "pets",
    "/marketplace/blacksmith": "forge", "/marketplace/store": "store", "/marketplace/creations": "creations",
    "/marketplace/trade": "trades", "/marketplace/auction": "auction", "/marketplace/credit": "credit",
    "/marketplace/track": "rewards", "/marketplace/badges": "badges", "/marketplace/leaderboard": "ranks",
    "/marketplace/invite": "invite", "/marketplace/friends": "friends", "/marketplace/inbox": "inbox",
    "/marketplace/play": "home", "/marketplace/customize": "customize", "/marketplace/profile": "profile",
    "/marketplace/fishing": "fishing", "/marketplace/mining": "mining", "/marketplace/dungeons": "delves",
};

// One icon, with the old emoji/react-icon kept as the fallback: a missing or not-yet-generated PNG degrades to
// exactly what shipped before rather than to a blank gap.
function NavIcon({ l, size, big = false }) {
    const [failed, setFailed] = useState(false);
    const k = NAV_SPRITE[l.href];
    const fallback = l.Icon
        ? <l.Icon className={big ? undefined : "game-nav-ico"} aria-hidden="true" />
        : l.sprite === "helmet" ? <SetsHelmet size={size} /> : <span aria-hidden="true">{l.emoji}</span>;
    if (!k || failed) return fallback;
    return (
        // eslint-disable-next-line @next/next/no-img-element
        <img
            className="game-nav-sprite" src={`/images/nav/${k}.png`} alt="" aria-hidden="true"
            width={size} height={size} style={{ width: size, height: size }} onError={() => setFailed(true)}
        />
    );
}
const renderIcon = (l) => <NavIcon l={l} size={18} />;
const renderBigIcon = (l) => <NavIcon l={l} size={28} big />;

// In-game menu bar: a horizontal, scrollable strip of the game areas + a pinned button that opens a full,
// CATEGORIZED grid menu of everything. Mounted once in the marketplace layout; self-hides on non-game pages.
const LINKS = [
    { href: "/marketplace/play", emoji: "🎮", label: "Home" },
    { href: "/marketplace/guide", emoji: "🧭", label: "Guide" },
    { href: "/marketplace/changelog", emoji: "📜", label: "What's New" },
    { href: "/marketplace/profile", emoji: "👤", label: "Profile" },
    { href: "/marketplace/customize", emoji: "🧑‍🎨", label: "Customize" },
    { href: "/marketplace/boss", emoji: "⚔️", label: "Boss" },
    { href: "/marketplace/sailing", emoji: "⛵", label: "Sailing" },
    { href: "/marketplace/spin", Icon: FaDharmachakra, label: "Spin" },
    { href: "/marketplace/pets", emoji: "🐾", label: "Pets" },
    { href: "/marketplace/inventory", emoji: "🛡️", label: "Gear" },
    { href: "/marketplace/store", emoji: "🛒", label: "Store" },
    { href: "/marketplace/sets", sprite: "helmet", label: "Sets" },
    { href: "/marketplace/quests", emoji: "📜", label: "Quests" },
    { href: "/marketplace/track", emoji: "🏆", label: "Rewards" },
    { href: "/marketplace/badges", emoji: "🎖️", label: "Badges" },
    { href: "/marketplace/leaderboard", emoji: "🥇", label: "Ranks" },
    { href: "/marketplace/bounties", emoji: "🎯", label: "Bounties" },
    { href: "/marketplace/invite", emoji: "🎁", label: "Invite" },
    { href: "/marketplace/creations", emoji: "🎨", label: "Creations" },
    { href: "/marketplace/credit", emoji: "💳", label: "Credit" },
];

const isOn = (pathname, href) => pathname === href || pathname.startsWith(`${href}/`);

// The game-path list lives in lib/marketplace/game-paths.js so the nav and the Pathfinder strip can never
// disagree about what counts as being in the game.

export default function GameNav() {
    const pathname = usePathname() || "";
    const [menuOpen, setMenuOpen] = useState(false);
    const [signedIn, setSignedIn] = useState(false); // gates the Town link + the one-time Forge announcement — declared before `links`
    // The Kitchen is owner-gated. The nav asks the server rather than deciding locally, because "am I the owner"
    // isn't something the client knows and shouldn't be something it guesses.
    const [kitchen, setKitchen] = useState(false);
    // DISHES you could cook right now. Prep recipes are excluded on purpose: a prep makes an ingredient for
    // something else, so badging it would nag you toward busywork rather than toward the thing that pays.
    const [dishesReady, setDishesReady] = useState(0);
    // The Mine is owner-gated while it's being built. Same contract as the Kitchen: ask the server, never guess,
    // and a non-owner simply has no Mine in the menu with nothing to see.
    const [mine, setMine] = useState(false);
    const [mineTrips, setMineTrips] = useState(0);
    useEffect(() => {
        let dead = false;
        fetch("/api/marketplace/mining", { cache: "no-store", credentials: "same-origin" })
            .then((r) => r.json())
            .then((d) => { if (!dead && d?.unlocked) { setMine(true); setMineTrips(Number(d?.trips?.left) || 0); } })
            .catch(() => { /* no mine, no menu entry */ });
        return () => { dead = true; };
    }, [pathname]);

    // The Arena, same contract as the Mine and the Dungeons: ask the server, never guess. A non-owner simply
    // has no Arena entry while it is still owner-gated.
    const [arena, setArena] = useState(false);
    const [arenaFights, setArenaFights] = useState(0);
    useEffect(() => {
        let dead = false;
        fetch("/api/marketplace/arena", { cache: "no-store", credentials: "same-origin" })
            .then((r) => r.json())
            .then((d) => { if (!dead && d?.unlocked) { setArena(true); setArenaFights(Number(d?.fightsLeft) || 0); } })
            .catch(() => { /* no arena, no menu entry */ });
        return () => { dead = true; };
    }, [pathname]);

    // Delves, same contract as the Mine: ask the server, never guess. A non-owner simply has no Delves entry.
    const [delves, setDelves] = useState(false);
    const [delveRuns, setDelveRuns] = useState(0);
    useEffect(() => {
        let dead = false;
        fetch("/api/marketplace/delves", { cache: "no-store", credentials: "same-origin" })
            .then((r) => r.json())
            .then((d) => { if (!dead && d?.unlocked) { setDelves(true); setDelveRuns((d?.dungeons || []).filter((x) => x.unlocked && !x.runToday).length); } })
            .catch(() => { /* no delves, no menu entry */ });
        return () => { dead = true; };
    }, [pathname]);
    // Every failure mode here looks identical to "you're not the owner" — a dropped request, a cached reply from
    // before you signed in, a blip in the route — and the Kitchen just isn't in the menu, with nothing to see.
    // So: never cached, and one retry before believing a negative.
    useEffect(() => {
        let dead = false;
        const ask = async (attempt = 0) => {
            try {
                const r = await fetch("/api/marketplace/cooking", { cache: "no-store", credentials: "same-origin" });
                const d = await r.json();
                if (dead) return;
                if (d?.unlocked) {
                    setKitchen(true);
                    // This response is the whole kitchen already — the badge count rides along for free rather
                    // than costing a second request. Only DISHES you can actually make right now: a badge you
                    // can't act on is the kind people learn to ignore. The old "and only if you have a cook
                    // left today" half of that test is gone with the daily cap — having the ingredients IS the
                    // whole condition now.
                    setDishesReady((d.recipes || []).filter((x) => x.kind === "dish" && x.canCook).length);
                    return;
                }
                // A negative on the first go is retried once — the common cause is the session cookie not being
                // live yet on a fresh sign-in, and a wrong "no" here is invisible rather than noisy.
                if (attempt === 0) setTimeout(() => { if (!dead) ask(1); }, 1200);
            } catch {
                if (!dead && attempt === 0) setTimeout(() => { if (!dead) ask(1); }, 1200);
            }
        };
        ask();
        // Cooking a dish spends the ingredients, so the badge has to be able to go DOWN without a navigation —
        // otherwise it sits there insisting on a dish you just made.
        const onRefresh = () => ask(1); // 1 = don't re-arm the sign-in retry; we already know the answer
        window.addEventListener("wolfden-hud-refresh", onRefresh);
        return () => { dead = true; window.removeEventListener("wolfden-hud-refresh", onRefresh); };
    }, [pathname]);
    // (Fishing was owner-gated at launch prep; it's public now and rides `signedIn` like Town.)
    // Farm + Forge + Auction + Town are all live for every signed-in member now.
    const links = [...LINKS, { href: "/marketplace/farm", emoji: "🏡", label: "Farm" }, { href: "/marketplace/blacksmith", emoji: "🔨", label: "Forge" },
        { href: "/marketplace/auction", emoji: "🏛️", label: "Auction" },
        ...(signedIn ? [{ href: "/marketplace/town", emoji: "🏘️", label: "Town" }] : []),
        ...(signedIn ? [{ href: "/marketplace/fishing", emoji: "🎣", label: "Fishing" }] : []),
        ...(kitchen ? [{ href: "/marketplace/cooking", emoji: "🍳", label: "Kitchen" }] : []),
        ...(mine ? [{ href: "/marketplace/mining", emoji: "⛏️", label: "Mine" }] : []),
        ...(delves ? [{ href: "/marketplace/dungeons", emoji: "🗝️", label: "Dungeons" }] : []),
        ...(arena ? [{ href: "/marketplace/arena", emoji: "⚔️", label: "Arena" }] : [])];
    const inGame = links.some((l) => isOn(pathname, l.href)) || isGamePath(pathname);

    // Measure what the strip has to sit under. The site header is sticky and its height moves with the
    // announcement banner and the viewport, so the offsets are read from the DOM and refreshed on resize
    // rather than pinned to a magic number that only holds on one phone.
    useEffect(() => {
        const body = document.body;
        if (!inGame) { body.classList.remove("in-game"); return undefined; }
        body.classList.add("in-game");
        const measure = () => {
            const hdr = document.querySelector(".site-header")?.getBoundingClientRect().height || 0;
            const hud = document.querySelector(".hud-strip")?.getBoundingClientRect().height || 0;
            document.documentElement.style.setProperty("--gnav-hdr", `${Math.round(hdr)}px`);
            document.documentElement.style.setProperty("--gnav-top", `${Math.round(hdr + hud)}px`);
        };
        measure();
        const ro = typeof ResizeObserver === "function" ? new ResizeObserver(measure) : null;
        const hdrEl = document.querySelector(".site-header");
        const hudEl = document.querySelector(".hud-strip");
        if (ro && hdrEl) ro.observe(hdrEl);
        if (ro && hudEl) ro.observe(hudEl);
        window.addEventListener("resize", measure);
        return () => {
            body.classList.remove("in-game");
            window.removeEventListener("resize", measure);
            ro?.disconnect();
        };
    }, [inGame, pathname]);

    const [chests, setChests] = useState(0);
    const [consumables, setConsumables] = useState(0); // unused potions/treats/relics — the Gear badge counts these too
    const [townTodo, setTownTodo] = useState(null); // { total, quests, well, tavern, event } from the town
    const [spins, setSpins] = useState(0);
    const [bossStrikes, setBossStrikes] = useState(0);
    const [questsReady, setQuestsReady] = useState(0);
    const [cropsReady, setCropsReady] = useState(0);
    const [petNudge, setPetNudge] = useState(0); // own pets you can still pet today (free daily reward)
    const [sailAttn, setSailAttn] = useState(false);
    const [castsLeft, setCastsLeft] = useState(0); // unthrown fishing casts — nudges people back to the rail
    const [forgeReady, setForgeReady] = useState(0); // chests the shards in your hold can already forge
    const [featureClaims, setFeatureClaims] = useState({}); // claimable per-feature daily quests {farm,sailing,forge}
    useEffect(() => {
        if (!inGame) return undefined;
        let alive = true;
        const loadChests = () => {
            fetch("/api/marketplace/chests", { cache: "no-store" }).then((r) => (r.ok ? r.json() : null)).then((d) => { if (alive) setChests((d?.chests || []).reduce((s, c) => s + (c.count || 0), 0)); }).catch(() => {});
            fetch("/api/marketplace/spin", { cache: "no-store" }).then((r) => (r.ok ? r.json() : null)).then((d) => { if (!alive) return; setSignedIn(Boolean(d?.signedIn)); if (d?.signedIn) setSpins((d.freeAvailable ? 1 : 0) + (d.tokens || 0)); }).catch(() => {});
            fetch("/api/marketplace/boss/strikes", { cache: "no-store" }).then((r) => (r.ok ? r.json() : null)).then((d) => { if (alive) setBossStrikes(d?.attacksLeft || 0); }).catch(() => {});
            fetch("/api/marketplace/quests", { cache: "no-store" }).then((r) => (r.ok ? r.json() : null)).then((d) => { if (!alive) return; const qs = Array.isArray(d) ? d : (d?.quests || []); setQuestsReady(qs.filter((q) => q.done && !q.claimed).length); }).catch(() => {});
            // The status route has always returned `casts` (and now `forgeable`); this used to read only
            // `attention`, which quietly made the cast badge below dead code.
            fetch("/api/marketplace/sailing/status", { cache: "no-store" }).then((r) => (r.ok ? r.json() : null)).then((d) => { if (!alive) return; setSailAttn(Boolean(d?.attention)); setCastsLeft(d?.casts || 0); setForgeReady(d?.forgeable || 0); }).catch(() => {});
            fetch("/api/marketplace/feature-daily?counts=1", { cache: "no-store" }).then((r) => (r.ok ? r.json() : null)).then((d) => { if (alive && d?.counts) setFeatureClaims(d.counts); }).catch(() => {});
            fetch("/api/marketplace/consumables", { cache: "no-store" }).then((r) => (r.ok ? r.json() : null)).then((d) => { if (alive) setConsumables((d?.stash || []).reduce((s2, c) => s2 + (c.count || 0), 0)); }).catch(() => {});
            // Town is the one hub whose tasks are invisible from outside it — the pint, a claimable bounty and
            // the wish all sit behind a door you have to walk through. `todo=1` returns the counts alone rather
            // than the whole plaza, so the pill costs a small query and not a full town render.
            fetch("/api/marketplace/town?todo=1", { cache: "no-store" }).then((r) => (r.ok ? r.json() : null)).then((d) => { if (alive && d?.todo) setTownTodo(d.todo); }).catch(() => {});
        };
        loadChests();
        const onRefresh = () => loadChests();
        window.addEventListener("wolfden-hud-refresh", onRefresh);
        return () => { alive = false; window.removeEventListener("wolfden-hud-refresh", onRefresh); };
    }, [inGame, pathname]);
    useEffect(() => {
        if (!inGame) return undefined;
        let alive = true;
        const load = () => fetch("/api/marketplace/farm", { cache: "no-store" }).then((r) => (r.ok ? r.json() : null)).then((d) => { if (!alive) return; setCropsReady(d?.garden?.readyCount || 0); setPetNudge(d?.petNudge || 0); }).catch(() => {});
        load();
        const onRefresh = () => load();
        window.addEventListener("wolfden-hud-refresh", onRefresh);
        return () => { alive = false; window.removeEventListener("wolfden-hud-refresh", onRefresh); };
    }, [inGame, pathname]);

    // Robustly pin the background while the full menu is open (overflow:hidden alone leaks scroll on mobile).
    useScrollLock(menuOpen);
    // Close on Escape.
    useEffect(() => {
        if (!menuOpen) return undefined;
        const onKey = (e) => { if (e.key === "Escape") setMenuOpen(false); };
        window.addEventListener("keydown", onKey);
        return () => window.removeEventListener("keydown", onKey);
    }, [menuOpen]);

    if (!inGame) return null;

    const plural = (n, w) => `${n} ${w}${n === 1 ? "" : "s"}`;
    const badgeInfo = (href) => {
        // Gear counts chests AND unused consumables: both are "you own something you haven't spent".
        if (href === "/marketplace/inventory" && (chests + consumables) > 0) {
            const bits = [];
            if (chests > 0) bits.push(plural(chests, "chest") + " to open");
            if (consumables > 0) bits.push(plural(consumables, "item") + " to use");
            return { badge: chests + consumables, title: bits.join(" · ") };
        }
        if (href === "/marketplace/boss" && bossStrikes > 0) return { badge: bossStrikes, title: `${plural(bossStrikes, "strike")} ready` };
        if (href === "/marketplace/spin" && spins > 0) return { badge: spins, title: `${plural(spins, "spin")} ready` };
        if (href === "/marketplace/quests" && questsReady > 0) return { badge: questsReady, title: `${plural(questsReady, "quest")} to claim` };
        // Feature pills also badge their claimable daily-quests (farm crops + quests together).
        if (href === "/marketplace/farm") { const n = cropsReady + petNudge + (featureClaims.farm || 0); if (n > 0) return { badge: n, title: [cropsReady ? `${plural(cropsReady, "crop")} ready` : null, petNudge ? `${plural(petNudge, "pet")} to pet` : null, featureClaims.farm ? `${plural(featureClaims.farm, "quest")} to claim` : null].filter(Boolean).join(" · ") }; }
        // Sailing badges everything waiting on you out there, summed like the farm pill: unthrown casts
        // (fishing happens during a voyage nobody watches, so the free casts quietly expire), claimable
        // dailies, and chests your shards can already forge. The forge one is the reason this stopped
        // picking a single winner — shards never expire, so a "highest priority only" rule meant a chest
        // sitting fully paid for showed nothing the whole time anything else was pending.
        if (href === "/marketplace/sailing") {
            const n = castsLeft + (featureClaims.sailing || 0) + forgeReady;
            if (n > 0) {
                return {
                    badge: n,
                    title: [
                        castsLeft ? `${plural(castsLeft, "cast")} left — your line's out` : null,
                        featureClaims.sailing ? `${plural(featureClaims.sailing, "quest")} to claim` : null,
                        forgeReady ? `${plural(forgeReady, "chest")} ready to forge` : null,
                    ].filter(Boolean).join(" · "),
                };
            }
        }
        if (href === "/marketplace/town" && (townTodo?.total || 0) > 0) {
            return {
                badge: townTodo.total,
                title: [
                    townTodo.event ? "a fight is on in the plaza" : null,
                    townTodo.quests ? `${plural(townTodo.quests, "bounty")} to claim` : null,
                    townTodo.tavern ? "your pint is waiting" : null,
                    townTodo.well ? "you haven't wished today" : null,
                ].filter(Boolean).join(" · "),
            };
        }
        // The Mine, the Dungeons and the Arena all hand out a daily allowance and all three were silent about
        // it — the only features in the menu with something waiting and no way to know from here.
        if (href === "/marketplace/mining" && mineTrips > 0) return { badge: mineTrips, title: `${plural(mineTrips, "trip")} down the mine` };
        if (href === "/marketplace/dungeons" && delveRuns > 0) return { badge: delveRuns, title: `${plural(delveRuns, "dungeon")} you haven't run today` };
        if (href === "/marketplace/arena" && arenaFights > 0) return { badge: arenaFights, title: `${plural(arenaFights, "challenge")} left today` };
        if (href === "/marketplace/fishing" && castsLeft > 0) return { badge: castsLeft, title: `${plural(castsLeft, "cast")} left today` };
        if (href === "/marketplace/blacksmith" && (featureClaims.forge || 0) > 0) return { badge: featureClaims.forge, title: `${plural(featureClaims.forge, "quest")} to claim` };
        // The Kitchen only nags you about DISHES you have every ingredient for — preps just make ingredients
        // for other recipes, and badging those would point you at the chore instead of the payoff.
        // (not plural() — that would say "dishs")
        if (href === "/marketplace/cooking" && dishesReady > 0) return { badge: dishesReady, title: `${dishesReady} dish${dishesReady === 1 ? "" : "es"} you can cook` };
        return { badge: null, title: null };
    };
    const dotFor = (href) => href === "/marketplace/sailing" && sailAttn;

    // The full, categorized grid menu — organized so you can see everything at once.
    const SECTIONS = [
        { title: "Play", items: [
            ...(signedIn ? [{ href: "/marketplace/town", emoji: "🏘️", label: "Town", sub: "Gather & raid" }] : []),
            { href: "/marketplace/boss", emoji: "⚔️", label: "Boss Fight", sub: "Join the raid" },
            { href: "/marketplace/sailing", emoji: "⛵", label: "Sailing", sub: "Voyage & dig" },
            { href: "/marketplace/farm", emoji: "🏡", label: "Farm", sub: "Grow & harvest" },
            { href: "/marketplace/spin", Icon: FaDharmachakra, label: "Daily Spin", sub: "Spin the wheel" },
            { href: "/marketplace/quests", emoji: "📜", label: "Quests", sub: "Daily bounties" },
            { href: "/marketplace/bounties", emoji: "🎯", label: "Bounties", sub: "Post & claim" },
            ...(signedIn ? [{ href: "/marketplace/fishing", emoji: "🎣", label: "Fishing", sub: "Log & records" }] : []),
            // The Kitchen is owner-gated. It has to be in the MENU as well as the scroll bar — the bar runs off
            // the side of the screen and a new entry appended to the end of it is, in practice, invisible.
            ...(kitchen ? [{ href: "/marketplace/cooking", emoji: "🍳", label: "The Kitchen", sub: "Cook what you farm" }] : []),
            ...(mine ? [{ href: "/marketplace/mining", emoji: "⛏️", label: "The Mine", sub: "Swing for ore" }] : []),
            ...(delves ? [{ href: "/marketplace/dungeons", emoji: "🗝️", label: "Dungeons", sub: "Ten floors down" }] : []),
            ...(arena ? [{ href: "/marketplace/arena", emoji: "⚔️", label: "The Arena", sub: "Climb the pack" }] : []),
        ] },
        { title: "Gear & Pets", items: [
            { href: "/marketplace/inventory", emoji: "🛡️", label: "Your Gear", sub: "Equip items" },
            { href: "/marketplace/pets", emoji: "🐾", label: "Pets", sub: "Collect & equip" },
            { href: "/marketplace/sets", sprite: "helmet", label: "Sets", sub: "Set bonuses" },
            { href: "/marketplace/blacksmith", emoji: "🔨", label: "The Forge", sub: "Salvage & enhance" },
        ] },
        { title: "Shop & Trade", items: [
            { href: "/marketplace/store", emoji: "🛒", label: "Store", sub: "Buy supplies" },
            { href: "/marketplace/creations", emoji: "🎨", label: "Creations", sub: "Custom AI art" },
            { href: "/marketplace/trade", emoji: "🤝", label: "Trades", sub: "Swap gear & gold" },
            { href: "/marketplace/auction", emoji: "🏛️", label: "Auction House", sub: "List & buy gear" },
            { href: "/marketplace/credit", emoji: "💳", label: "Store Credit", sub: "Credit + coins" },
        ] },
        { title: "Progress & Social", items: [
            { href: "/marketplace/track", emoji: "🏆", label: "Rewards", sub: "Reward track" },
            { href: "/marketplace/badges", emoji: "🎖️", label: "Badges", sub: "Earn & show off" },
            { href: "/marketplace/leaderboard", emoji: "🥇", label: "Ranks", sub: "Leaderboard" },
            { href: "/marketplace/invite", emoji: "🎁", label: "Invite", sub: "500 gold each" },
            { href: "/marketplace/friends", emoji: "👥", label: "Friends", sub: "Add & message" },
            { href: "/marketplace/inbox", emoji: "✉️", label: "Inbox", sub: "Messages" },
        ] },
        { title: "You", items: [
            { href: "/marketplace/play", emoji: "🎮", label: "Game Home", sub: "The hub" },
            { href: "/marketplace/customize", emoji: "🧑‍🎨", label: "Customize", sub: "Avatar & card look" },
            { href: "/marketplace/profile", emoji: "👤", label: "Profile", sub: "Settings & account" },
        ] },
    ];

    return (
        <>
            {signedIn ? <ForgeAnnounce /> : null}
            {/* Mounted on the NAV, not on a page, so a launch card reaches people wherever they resume — most
                sessions do not start on the home screen. */}
            {signedIn ? <AnnouncementModal /> : null}
            {signedIn ? <FishingLaunch /> : null}
            {signedIn ? <MiningLaunch /> : null}
            {signedIn ? <DungeonLaunch /> : null}
            {signedIn ? <SurveyModal /> : null}
            <style>{GAMENAV_CSS}</style>
            <nav className="game-nav" aria-label="Game menu">
                <div className="game-nav-scroll">
                    <button type="button" className="game-nav-menu-btn" aria-label="Open full menu" aria-expanded={menuOpen} onClick={() => setMenuOpen(true)}>
                        <svg width="17" height="17" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><rect x="3" y="3" width="7.5" height="7.5" rx="1.6" /><rect x="13.5" y="3" width="7.5" height="7.5" rx="1.6" /><rect x="3" y="13.5" width="7.5" height="7.5" rx="1.6" /><rect x="13.5" y="13.5" width="7.5" height="7.5" rx="1.6" /></svg>
                        Menu
                    </button>
                    {links.map((l) => {
                        const { badge, title } = badgeInfo(l.href);
                        const dot = dotFor(l.href);
                        return (
                            <Link key={l.href} href={l.href} className={`game-nav-link${isOn(pathname, l.href) ? " is-active" : ""}${badge ? " has-badge" : ""}${dot ? " has-dot" : ""}`}>
                                {renderIcon(l)} {l.label}
                                {badge ? <span className="game-nav-badge" title={title}>{badge}</span> : null}
                                {dot ? <span className="game-nav-dot" title="Your boat has landed — time to dig!" aria-label="needs attention" /> : null}
                            </Link>
                        );
                    })}
                </div>
            </nav>

            {menuOpen ? (
                <div className="gm-overlay" onClick={() => setMenuOpen(false)} role="presentation">
                    <div className="gm-panel" onClick={(e) => e.stopPropagation()} role="dialog" aria-label="All game areas">
                        <div className="gm-head">
                            <strong>Where to?</strong>
                            <button type="button" className="gm-close" aria-label="Close menu" onClick={() => setMenuOpen(false)}>×</button>
                        </div>
                        <div className="gm-body">
                            {SECTIONS.map((sec) => (
                                <div key={sec.title} className="gm-section">
                                    <div className="gm-section-title">{sec.title}</div>
                                    <div className="gm-grid">
                                        {sec.items.map((it) => {
                                            const { badge, title } = badgeInfo(it.href);
                                            const dot = dotFor(it.href);
                                            return (
                                                <Link key={it.href} href={it.href} className={`gm-tile${isOn(pathname, it.href) ? " is-active" : ""}${it.owner ? " is-owner" : ""}`} onClick={() => setMenuOpen(false)}>
                                                    <span className="gm-tile-ico">{renderBigIcon(it)}</span>
                                                    <span className="gm-tile-label">{it.label}</span>
                                                    <span className="gm-tile-sub">{it.sub}</span>
                                                    {it.owner ? <span className="gm-tile-owner">owner</span> : null}
                                                    {badge ? <span className="gm-tile-badge" title={title}>{badge}</span> : null}
                                                    {dot ? <span className="gm-tile-dot" title="Needs attention" /> : null}
                                                </Link>
                                            );
                                        })}
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>
                </div>
            ) : null}
        </>
    );
}

const GAMENAV_CSS = `
/* ── THE MENU STAYS PUT ──────────────────────────────────────────────────────────────────────────────────────
   In game, the HUD and the menu strip used to scroll away with the page: three screens down a gear grid there
   was no coin count, no level, and no way anywhere else without scrolling all the way back up. Both now stick
   under the site header while you are in the game (the class is only on the body on game paths, so the shop
   and the rest of the site are untouched).

   The offsets are measured, not guessed — the header's height changes with the announcement banner, the
   viewport width and the font, and a hard-coded top lands the strip either overlapping the logo or floating
   below it with a stripe of page showing through. */
body.in-game .hud-strip { position: sticky; top: var(--gnav-hdr, 0px); z-index: 9; backdrop-filter: blur(9px);
    background: linear-gradient(90deg, rgba(28,24,14,0.94), rgba(20,18,12,0.94)); }
body.in-game .game-nav { position: sticky; top: var(--gnav-top, 0px); z-index: 8; padding: 6px 7px 2px;
    margin-left: -7px; margin-right: -7px; border-radius: 0 0 13px 13px;
    /* Opaque, not a fade: a translucent tail let the page's text read straight through the strip. */
    background: #0e0e0e; border-bottom: 1px solid rgba(255,215,94,0.16);
    box-shadow: 0 10px 20px -14px rgba(0,0,0,1); }
/* Nav sprites sit on the same baseline the emoji did, so swapping them in doesn't shift any row. */
.game-nav-sprite { display: inline-block; object-fit: contain; vertical-align: -0.28em; flex: 0 0 auto; }
.gm-item .game-nav-sprite { vertical-align: middle; }
.game-nav-menu-btn { position: sticky; left: 0; z-index: 3; flex: 0 0 auto; display: inline-flex; align-items: center; gap: 6px; padding: 7px 12px; margin-right: 4px;
    border: none; border-radius: 10px; cursor: pointer; font-weight: 800; font-size: 13px; white-space: nowrap;
    color: #1c130a; background: linear-gradient(180deg, #ffd75e, #f3b23a); box-shadow: 0 2px 0 #b57f22, 3px 0 10px 2px rgba(0,0,0,0.45); }
.game-nav-menu-btn:active { transform: translateY(1px); }
.game-nav-menu-btn svg { display: block; }
.gm-overlay { position: fixed; inset: 0; z-index: 10070; background: rgba(6,8,12,0.72); backdrop-filter: blur(3px); display: flex; align-items: flex-end; justify-content: center; padding: 0; animation: gmFade .18s ease both; }
@keyframes gmFade { from { opacity: 0; } to { opacity: 1; } }
.gm-panel { width: 100%; max-width: 640px; max-height: 88dvh; display: flex; flex-direction: column; border-radius: 20px 20px 0 0; overflow: hidden;
    background: linear-gradient(180deg, #1a1d24, #12141a); border: 1px solid rgba(255,215,110,0.25); border-bottom: none; box-shadow: 0 -16px 50px rgba(0,0,0,0.6); animation: gmUp .26s cubic-bezier(.2,1,.3,1) both; }
@keyframes gmUp { from { transform: translateY(40px); opacity: 0.4; } to { transform: translateY(0); opacity: 1; } }
.gm-head { display: flex; align-items: center; padding: 14px 16px 10px; }
.gm-head strong { font-size: 17px; color: #ffe0b0; }
.gm-close { margin-left: auto; width: 32px; height: 32px; border-radius: 999px; border: none; background: rgba(255,255,255,0.08); color: #e8e2d6; font-size: 20px; cursor: pointer; line-height: 1; }
.gm-body { overflow-y: auto; padding: 0 14px 20px; -webkit-overflow-scrolling: touch; }
.gm-section { margin-top: 12px; }
.gm-section-title { font-size: 11px; font-weight: 800; letter-spacing: 0.06em; text-transform: uppercase; color: #9fb0c0; margin: 0 4px 8px; }
.gm-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(94px, 1fr)); gap: 9px; }
.gm-tile { position: relative; display: flex; flex-direction: column; align-items: center; gap: 2px; padding: 12px 6px 10px; border-radius: 15px; text-align: center; text-decoration: none;
    background: linear-gradient(180deg, rgba(255,255,255,0.06), rgba(255,255,255,0.02)); border: 1px solid rgba(255,255,255,0.09); color: #eef2f7; transition: transform .12s ease, box-shadow .12s ease, border-color .12s ease; }
.gm-tile:hover { transform: translateY(-2px); border-color: rgba(255,215,110,0.5); box-shadow: 0 6px 18px rgba(0,0,0,0.45); }
.gm-tile.is-active { border-color: #ffd75e; background: linear-gradient(180deg, rgba(255,215,94,0.16), rgba(255,215,94,0.05)); }
.gm-tile.is-owner { border-color: rgba(255,150,60,0.5); }
.gm-tile-ico { font-size: 26px; line-height: 1; height: 30px; display: grid; place-items: center; }
.gm-tile-ico svg { width: 26px; height: 26px; }
.gm-tile-label { font-size: 12.5px; font-weight: 800; line-height: 1.1; }
.gm-tile-sub { font-size: 9.5px; color: #9fb0c0; line-height: 1.15; }
.gm-tile-owner { position: absolute; top: 6px; left: 6px; font-size: 8px; font-weight: 800; text-transform: uppercase; letter-spacing: 0.05em; color: #ffb877; background: rgba(255,140,60,0.18); border: 1px solid rgba(255,140,60,0.5); border-radius: 999px; padding: 0 5px; }
.gm-tile-badge { position: absolute; top: 6px; right: 6px; min-width: 17px; height: 17px; padding: 0 4px; border-radius: 999px; background: #e0433f; color: #fff; font-size: 10px; font-weight: 900; display: grid; place-items: center; box-shadow: 0 1px 4px rgba(0,0,0,0.5); }
.gm-tile-dot { position: absolute; top: 8px; right: 8px; width: 9px; height: 9px; border-radius: 50%; background: #ff9a3c; box-shadow: 0 0 8px #ff9a3c; }
`;
