"use client";

import { useState } from "react";

import PetEnshrine from "@/components/PetEnshrine";

// ── THE ENSHRINE LAB ─────────────────────────────────────────────────────────────────────────────────────────
// Dev only. Mounts the REAL panel against fixture state, so every branch it has can be looked at without
// needing a member who happens to have a level-6 pet and a stone in hand — which, given level 6 is six weeks of
// work, would otherwise mean the panel could not be seen at all until long after it shipped.
//
// The four states are the whole surface: ready with both stones, ready with one, ready with none (the common
// one, and the one that has to sell the dig), and already enshrined.
const PET = { id: "wolf_pup", name: "Wolf Pup", rarity: "common", color: "#cbd5e1" };

// The two forms, as generated by scripts/gen-pet-level6.mjs. Local files so the lab works with no database.
const SPRITES = {
    light: { url: "/images/lab/wolf_pup-lv6-light.png", flip: false },
    dark: { url: "/images/lab/wolf_pup-lv6-dark.png", flip: false },
};

const CASES = [
    { key: "both", label: "Ready · both stones", stones: { light: 2, dark: 1 }, enshrined: null, level: 6 },
    { key: "one", label: "Ready · one stone", stones: { light: 0, dark: 1 }, enshrined: null, level: 6 },
    { key: "none", label: "Ready · no stones", stones: { light: 0, dark: 0 }, enshrined: null, level: 6 },
    { key: "light", label: "Enshrined · Lightstone", stones: { light: 0, dark: 0 }, enshrined: "light", level: 6 },
    { key: "dark", label: "Enshrined · Darkstone", stones: { light: 0, dark: 0 }, enshrined: "dark", level: 6 },
    { key: "five", label: "Level 5 — panel absent", stones: { light: 1, dark: 1 }, enshrined: null, level: 5 },
];

export default function PetEnshrineLab() {
    const [which, setWhich] = useState("both");
    const [log, setLog] = useState([]);
    const c = CASES.find((x) => x.key === which) || CASES[0];

    return (
        <div className="pelab">
            <h1 className="pelab-h">Enshrine lab</h1>
            <div className="pelab-tabs">
                {CASES.map((x) => (
                    <button key={x.key} type="button" className={`pelab-tab${which === x.key ? " is-on" : ""}`}
                        onClick={() => { setWhich(x.key); setLog([]); }}>
                        {x.label}
                    </button>
                ))}
            </div>

            <div className="pelab-stage">
                <PetEnshrine
                    pet={PET}
                    level={c.level}
                    sprites={SPRITES}
                    stones={c.stones}
                    prices={{ doubloons: 900, laurels: 6000 }}
                    enshrined={c.enshrined}
                    onEnshrine={(stone) => setLog((l) => [...l, `POST enshrine { petId: "${PET.id}", stone: "${stone}" }`])}
                />
                {c.level < 6 ? <p className="pelab-note">Nothing renders below level 6 — correct.</p> : null}
            </div>

            {log.length ? (
                <pre className="pelab-log">{log.join("\n")}</pre>
            ) : null}

            {/* The lab's own chrome lives in globals.css, NOT in a <style> tag here. A runtime <style>
                inside a client component trips a React 19 hydration mismatch, and the symptom is not a
                warning — it is that onClick never attaches and the page looks fine while being dead. Cost an
                hour on the Jeweller earlier; not paying it twice. */}
        </div>
    );
}
