import { db } from "../src/lib/db.js";
const all = await db.queryOne(`SELECT COALESCE(SUM(amount),0) AS b, COUNT(*) n FROM cash_ledger`);
const live = await db.queryOne(`SELECT COALESCE(SUM(amount),0) AS b, COUNT(*) n FROM cash_ledger WHERE already_counted = FALSE`);
const counted = await db.queryOne(`SELECT COALESCE(SUM(amount),0) AS b, COUNT(*) n FROM cash_ledger WHERE already_counted = TRUE`);
console.log(`  every row              $${Number(all.b).toFixed(2)}  (${all.n} rows)`);
console.log(`  already_counted=FALSE  $${Number(live.b).toFixed(2)}  (${live.n} rows)   <- what both screens ask for`);
console.log(`  already_counted=TRUE   $${Number(counted.b).toFixed(2)}  (${counted.n} rows)`);
const recent = await db.query(`SELECT occurred_on, description, amount, source, already_counted, created_at FROM cash_ledger ORDER BY created_at DESC LIMIT 12`);
console.log("\n  most recently written rows:");
for (const r of recent) console.log(`    ${String(r.occurred_on).slice(0,10)}  ${String(r.amount).padStart(9)}  ${r.already_counted ? "counted" : "live   "}  ${r.source.padEnd(8)} ${String(r.description).slice(0,42)}   written ${new Date(r.created_at).toISOString().slice(0,16)}`);
const counts = await db.query(`SELECT counted_at, actual, expected, delta FROM cash_count ORDER BY counted_at DESC LIMIT 5`).catch(() => []);
console.log("\n  last physical counts:");
for (const c of counts) console.log(`    ${new Date(c.counted_at).toISOString().slice(0,16)}  counted $${c.actual}  expected $${c.expected}  delta ${c.delta}`);
process.exit(0);
