import { db } from "../src/lib/db.js";
const A = await import("../src/lib/marketplace/arena.js");
const who = await db.queryOne(`SELECT id, display_name FROM mkt_buyer WHERE display_name = 'The Wolf Den'`);
const nav = await A.arenaNav(who.id);
console.log();
console.log(`  me: ${who.display_name}  fights left today: ${nav.fightsLeft}/${nav.fightsPerDay}`);
const st = await A.getArenaState(who.id);
const board = (st.board || []).filter((b) => !b.npc).slice(0, 8);
console.log(`  real members on the board: ${board.length}`);
for (const b of board) console.log(`   - ${String(b.name).padEnd(22)} vp ${String(b.vp).padStart(5)}  power ${b.power ?? "?"}  ${b.canFight === false ? "(cooldown)" : ""}`);
console.log();