import { partForTier } from "@/lib/marketplace/forge-parts.js";
import { shardCoin } from "@/lib/marketplace/dig-values.js";

// ── WHAT YOU MEET AT SEA ─────────────────────────────────────────────────────────────────────────────────────
//
// An encounter used to be a modal: you checked your phone, a box said "you met a kraken and salvaged its
// hide", and you tapped Nice. The single most dramatic thing that can happen mid-voyage resolved itself while
// you were not looking, and the ship you had spent weeks building had nothing to do with the outcome.
//
// They are FIGHTS now, on the same engine as the fleet ladder, using the guns you actually own. Your voyage
// stops dead until you deal with it, and your phone is told — because a fight that resolves without you is
// the thing this replaces.
//
// TWO SHAPES, and the difference is what you can shoot at:
//
//   ship     Another hull. Canvas, timber and a gun deck, exactly like a fleet ship — you pick the part.
//   monster  A living thing. It has no rigging and no gun ports, so there is nothing to target but the animal
//            itself; every ball goes into it. It still hits BACK across your whole ship, because a kraken
//            does not care which part of you it is breaking.
//
// Difficulty runs 1–5. A tier-1 meeting is a nuisance you can lose a plank to; a tier-5 is a genuine wall you
// may want to run from. The reward is a named one-off — nothing that outruns the Forge, but nothing you can
// get anywhere else either, so a rare encounter is a story rather than a fragment.

/** Named loot, keyed so the grant path and the recap agree. */
export const ENC_LOOT = {
    fragments: (n, tier) => ({ kind: "fragment", n, tier }),
    chest: (tier) => ({ kind: "chest", tier }),
    doubloons: (n) => ({ kind: "doubloons", n }),
    consumable: (id) => ({ kind: "consumable", id }),
    parts: (tier, n) => ({ kind: "parts", tier, n }),
    piece: (id) => ({ kind: "piece", id }),
};

const L = ENC_LOOT;

// `art` is generated by scripts/gen-encounters.mjs into /images/sailing/enc/<id>.png.
export const ENCOUNTERS = [
    // ── TIER 1 ── nuisances. Two or three volleys.
    { id: "gull_raiders", kind: "ship", tier: 1, name: "Gull Raiders", cls: "Fishing skiff",
        blurb: "Three lads, one stolen swivel gun and a great deal of confidence.",
        guns: 1, hits: 5, accuracy: 0.5, rake: 0.04, ammo: "round",
        loot: [L.doubloons(6), L.fragments(1, "wooden")] },
    { id: "reef_crabs", kind: "monster", tier: 1, name: "Reef Crawler", cls: "Shell-backed crab",
        blurb: "It has mistaken your hull for a rival. It is not entirely wrong.", limb: "crab",
        guns: 1, hits: 6, accuracy: 0.52, rake: 0.05, ammo: "round",
        loot: [L.fragments(2, "wooden"), L.consumable("treat_bone")] },
    { id: "salvage_scow", kind: "ship", tier: 1, name: "The Bilge Rat", cls: "Salvage scow",
        blurb: "Wreckers. They were hoping you were already sinking.",
        guns: 2, hits: 6, accuracy: 0.52, rake: 0.05, ammo: "round",
        loot: [L.doubloons(8), L.chest("wooden")] },
    { id: "gull_swarm", kind: "monster", tier: 1, name: "Storm Petrels", cls: "Screaming flock",
        blurb: "Hundreds of them, and every one wants what is in your hold.", limb: "swarm",
        guns: 3, hits: 4, accuracy: 0.44, rake: 0.03, ammo: "grape",
        loot: [L.fragments(2, "wooden"), L.doubloons(5)] },

    // ── TIER 2 ── a real exchange.
    { id: "brine_smugglers", kind: "ship", tier: 2, name: "Brine Runners", cls: "Smuggler's sloop",
        blurb: "Fast, low in the water, and carrying something they will not discuss.",
        guns: 3, hits: 9, accuracy: 0.56, rake: 0.07, ammo: "round",
        loot: [L.doubloons(14), L.chest("wooden"), L.consumable("spin_lucky_coin")] },
    { id: "glass_eels", kind: "monster", tier: 2, name: "Glass Eel Bloom", cls: "Swarm",
        blurb: "They chew the caulking out from between your planks while you watch.", limb: "swarm",
        guns: 4, hits: 8, accuracy: 0.5, rake: 0.05, ammo: "grape",
        loot: [L.fragments(3, "wooden"), L.consumable("treat_snack")] },
    { id: "tidewatch", kind: "ship", tier: 2, name: "Tidewatch", cls: "Revenue cutter",
        blurb: "They would like to inspect your cargo. You would like them not to.",
        guns: 3, hits: 11, accuracy: 0.58, rake: 0.08, ammo: "chain",
        loot: [L.doubloons(16), L.fragments(2, "iron")] },
    { id: "shalefin", kind: "monster", tier: 2, name: "Shalefin", cls: "Armoured ray",
        blurb: "It surfaces under you like a slab of moving slate.", limb: "jaws",
        guns: 2, hits: 13, accuracy: 0.55, rake: 0.1, ammo: "round",
        loot: [L.parts(1, 2), L.fragments(2, "iron")] },

    // ── TIER 3 ── you will feel this one.
    { id: "gravebell", kind: "ship", tier: 3, name: "The Gravebell", cls: "Ghost brig",
        blurb: "No crew answers the hail. The gun ports run out anyway.",
        guns: 5, hits: 16, accuracy: 0.62, rake: 0.11, ammo: "chain",
        loot: [L.doubloons(24), L.chest("iron"), L.consumable("stone_storm")] },
    // `limb` names what its arms are called; `guns` IS how many attacks it makes a turn, because the engine
    // gives a foe one order per live gun. The blurb said "three arms" while guns was 4 — the card and the
    // fight disagreed, and the fight was the honest one.
    { id: "kraken_young", kind: "monster", tier: 3, name: "Kraken Whelp", cls: "Young kraken",
        blurb: "Only a juvenile. Only four arms across your deck.", limb: "kraken",
        guns: 4, hits: 18, accuracy: 0.6, rake: 0.12, ammo: "round",
        loot: [L.parts(2, 3), L.consumable("treat_snack"), L.fragments(3, "iron")] },
    { id: "corsair_wolves", kind: "ship", tier: 3, name: "The Wolfpack", cls: "Corsair pair",
        blurb: "Two hulls working as one. They have done this a great many times.",
        guns: 6, hits: 15, accuracy: 0.64, rake: 0.13, ammo: "grape",
        loot: [L.doubloons(30), L.parts(2, 2)] },
    { id: "anglerdeep", kind: "monster", tier: 3, name: "The Lantern", cls: "Abyssal angler",
        blurb: "You saw the light first. That was the point of the light.", limb: "jaws",
        guns: 3, hits: 21, accuracy: 0.66, rake: 0.14, ammo: "explosive",
        loot: [L.chest("iron"), L.fragments(4, "iron")] },

    // ── TIER 4 ── a wall with a name.
    { id: "widowmaker", kind: "ship", tier: 4, name: "Widowmaker", cls: "Privateer frigate",
        blurb: "A letter of marque from a country that no longer exists.",
        guns: 7, hits: 24, accuracy: 0.68, rake: 0.15, ammo: "explosive",
        loot: [L.doubloons(44), L.chest("gold"), L.parts(3, 3)] },
    { id: "leviathan_old", kind: "monster", tier: 4, name: "Old Grief", cls: "Grey leviathan",
        blurb: "It has been hit before, by better ships than yours, and it is still here.", limb: "jaws",
        guns: 5, hits: 30, accuracy: 0.67, rake: 0.16, ammo: "round",
        loot: [L.parts(3, 4), L.fragments(4, "gold"), L.consumable("treat_snack")] },
    { id: "black_liturgy", kind: "ship", tier: 4, name: "Black Liturgy", cls: "Cult barque",
        blurb: "They are singing. They do not stop singing when you fire.",
        guns: 7, hits: 26, accuracy: 0.7, rake: 0.16, ammo: "chain",
        loot: [L.doubloons(48), L.consumable("scroll_ancient"), L.fragments(3, "gold")] },
    { id: "reef_drake", kind: "monster", tier: 4, name: "Reef Drake", cls: "Sea drake",
        blurb: "It nests in a wreck it made itself, and it is bored.", limb: "jaws",
        guns: 6, hits: 27, accuracy: 0.69, rake: 0.18, ammo: "explosive",
        loot: [L.chest("gold"), L.parts(3, 3)] },

    // ── TIER 5 ── run, or be a story.
    { id: "dread_corsair", kind: "ship", tier: 5, name: "The Dread Corsair", cls: "Black galleon",
        blurb: "The flag is courtesy. The broadside is the message.",
        // 9 -> 7. A player's broadside caps at SEVEN (gunsFor: 2 + the Cannons track's 5), so nine barrels was
        // a foe strictly beyond anything anybody could ever build toward. A wall you cannot out-equip is not
        // difficulty, it is a locked door with loot behind it.
        guns: 7, hits: 36, accuracy: 0.74, rake: 0.2, ammo: "explosive",
        loot: [L.doubloons(70), L.chest("mythic"), L.parts(4, 4)] },
    { id: "elder_kraken", kind: "monster", tier: 5, name: "The Elder", cls: "Elder kraken",
        blurb: "Every chart you own has the same word written over this water.", limb: "kraken",
        guns: 7, hits: 42, accuracy: 0.72, rake: 0.22, ammo: "round",
        loot: [L.parts(4, 5), L.chest("gold"), L.fragments(5, "mythic")] },
    { id: "drowned_admiral", kind: "ship", tier: 5, name: "The Drowned Admiral", cls: "Sunken flagship",
        blurb: "It went down with all hands nine years ago. It has come back up.",
        guns: 9, hits: 40, accuracy: 0.75, rake: 0.22, ammo: "chain",
        // ⚠️ THE CONSUMABLE'S OWN ID, NOT THE SHOP'S. This read "scroll_enchant", which is what the
        // QUARTERMASTER calls this scroll (sailing.js keeps a shop row whose `consumable` field maps it
        // across). CONSUMABLES has never had that key — the real one is forge_enchant_scroll — and
        // grantConsumable returns silently for an id it does not know, so sinking the Drowned Admiral paid
        // nothing and the victory card printed the raw slug where a name should be. See the note in
        // sailing.js: an unknown id is now logged rather than swallowed.
        loot: [L.doubloons(80), L.chest("mythic"), L.consumable("forge_enchant_scroll")] },
    { id: "world_serpent", kind: "monster", tier: 5, name: "The Long Coil", cls: "World serpent",
        blurb: "You can see two parts of it at once and they are very far apart.", limb: "serpent",
        guns: 8, hits: 46, accuracy: 0.73, rake: 0.24, ammo: "explosive",
        loot: [L.parts(5, 4), L.chest("mythic"), L.fragments(6, "mythic")] },
];

export const encounterById = (id) => ENCOUNTERS.find((e) => e.id === String(id)) || null;
export const encounterArt = (id) => `/images/sailing/enc/${id}.png`;

/**
 * Which parts of this foe you are allowed to shoot at.
 *
 * A monster has no rigging and no gun ports — there is nothing on it to take off, so every ball goes into the
 * animal. This is the whole mechanical difference between the two shapes, and it is why a monster fight is a
 * race rather than a dismantling: you cannot blunt it first.
 */
// A ship offers canvas, timber and barrels. A creature offers its body and its LIMBS — which resolve through
// the same "guns" slot in the engine (severing one removes an attack, exactly as dismounting a cannon does),
// so nothing downstream needs a second code path. Only the words and the markers change.
export const encounterZones = (enc) => (enc?.kind === "monster" ? ["hull", "guns"] : ["sails", "hull", "guns"]);

/**
 * A voyage's encounter marks. Each is a fraction of the trip at which something may be waiting.
 *
 * It used to be exactly one, at the halfway point, on a Fortune-scaled roll. Three chances now — a third of
 * the way, halfway, and two thirds — each rolled independently, so a quiet voyage is still the common case
 * but a bad one can go wrong more than once. The later marks are rarer than the first on purpose: two fights
 * in a trip should feel like luck, and three like a story.
 */
export const ENCOUNTER_MARKS = [
    { at: 0.34, weight: 1 },      // the first roll, at the full rate
    { at: 0.5, weight: 0.55 },    // a second, a bit better than half as likely
    { at: 0.68, weight: 0.25 },   // and a third, uncommon
];

// ── WHAT IS ON THE TABLE ─────────────────────────────────────────────────────────────────────────────────────
// The same list the payout walks, turned into something the screen can draw. Both sides read `enc.loot`, so the
// spoils you are shown before you commit and the spoils you are handed after cannot drift apart — which is the
// only reason to show them at all. No words beyond a name and a count: the sprite says what it is.
const TITLE = (s) => s.charAt(0).toUpperCase() + s.slice(1);

export function lootPreview(loot = [], chestArt = {}, consumables = {}) {
    return loot.map((l) => {
        if (l.kind === "doubloons") return { kind: "doubloons", n: l.n, name: "Doubloons", art: "/images/sailing/doubloon.png" };
        // Pays doubloons now (see grantSeaSpoils in sailing.js) — the preview has to say what actually lands.
        if (l.kind === "fragment") return { kind: "doubloons", n: shardCoin(l.tier, l.n), name: "doubloons", art: "/images/sailing/doubloon.png" };
        // Chest sprites are generated blobs, not files on disk — the caller already holds the map.
        if (l.kind === "chest") return { kind: "chest", n: 1, tier: l.tier, name: `${TITLE(l.tier)} chest`, art: chestArt[l.tier] || null };
        if (l.kind === "parts") { const p = partForTier(l.tier); return { kind: "parts", n: l.n, name: p?.name || `Tier ${l.tier}`, art: p?.sprite || null, color: p?.color }; }
        // A consumable that resolved to nothing used to fall through to the chest-icon fallback, so a Pet
        // Treat was advertised as a wooden chest. Both its name and its sprite come from the caller's maps.
        if (l.kind === "consumable") {
            const c = consumables[l.id] || {};
            return { kind: "consumable", n: 1, id: l.id, name: c.name || null, art: c.art || null, emoji: c.emoji || null };
        }
        return { kind: l.kind, n: l.n || 1, name: null, art: null };
    });
}
