// ── THE PIRATE FLEET ─────────────────────────────────────────────────────────────────────────────────────────
// The ladder ship battles are actually about. Raiding another member is a side action — it depends on who
// happens to be online, and beating a beginner pays what beating a rival pays — so the PROGRESSION is a fixed
// fleet of designed enemies you fight in order. Rank 1 is a fishing cutter that has taken up piracy; rank 15 is
// a flagship. Your `fleet_depth` is the highest rank you have sunk, and the next sortie is depth + 1.
//
// Losing costs you nothing but the sortie. A ladder that takes rungs away when you slip is a ladder people stop
// climbing, and this game does not punish (see the engagement notes) — the cost of losing is that you did not
// win yet.
//
// Every fifth rank is a NAMED ship: a wall with a captain, a story line, and a reward worth the wall. They are
// where the chest and the gear come from, so the fleet feeds the rest of the game rather than only itself.
//
// `art` is the sprite's file key; the hulls live in /public/images/fleet and are generated by
// scripts/gen-fleet-ships.mjs. They are drawn facing LEFT on purpose — the enemy stands on the right of the
// battle stage, and mirroring a hull in CSS mirrors its lighting with it.

export const FLEET = [
    { rank: 1, name: "Gull's Folly", cls: "Fishing cutter", art: "fleet_cutter", ammo: "round",
        hp: 78, guns: 2, accuracy: 0.52, rake: 0.05,
        flavor: "A fishing boat with two stolen guns lashed to the deck. It should not be out here." },
    { rank: 2, name: "Wet Powder", cls: "Smuggler's sloop", art: "fleet_sloop", ammo: "round",
        hp: 112, guns: 3, accuracy: 0.55, rake: 0.06,
        flavor: "Fast, low, and carrying more brandy than shot." },
    { rank: 3, name: "The Cormorant", cls: "Coastal lugger", art: "fleet_lugger", ammo: "grape",
        hp: 155, guns: 3, accuracy: 0.57, rake: 0.07,
        flavor: "Loads grape and sweeps decks. Stay behind your bulwarks." },
    { rank: 4, name: "Iron Nettle", cls: "Gun brig", art: "fleet_brig", ammo: "round",
        hp: 230, guns: 5, accuracy: 0.59, rake: 0.08,
        flavor: "Plated at the waterline with whatever the last wreck was carrying." },
    { rank: 5, name: "Salt Meg's Revenge", cls: "Brigantine", art: "fleet_boss_revenge", ammo: "chain", boss: true,
        hp: 280, guns: 6, accuracy: 0.62, rake: 0.11,
        flavor: "Meg takes your rigging first and your cargo at her leisure. Nobody has out-run her twice." },

    { rank: 6, name: "The Hollow Tide", cls: "Schooner", art: "fleet_schooner", ammo: "round",
        hp: 315, guns: 6, accuracy: 0.61, rake: 0.1,
        flavor: "Crewed thin and sailed hard. It will trade with you all afternoon." },
    { rank: 7, name: "Bitterhold", cls: "Corvette", art: "fleet_corvette", ammo: "explosive",
        hp: 355, guns: 7, accuracy: 0.63, rake: 0.12,
        flavor: "Fires shells. Half go wide; the half that don't set your deck alight." },
    { rank: 8, name: "Widow's Wage", cls: "Privateer frigate", art: "fleet_frigate", ammo: "grape",
        hp: 400, guns: 7, accuracy: 0.65, rake: 0.13,
        flavor: "A letter of marque from a country that no longer exists, and no intention of checking." },
    { rank: 9, name: "The Grinding Reef", cls: "Heavy frigate", art: "fleet_heavy", ammo: "round",
        hp: 440, guns: 8, accuracy: 0.67, rake: 0.13,
        flavor: "Slow, heavy, and entirely willing to sit there and out-last you." },
    { rank: 10, name: "The Black Tithe", cls: "Ship of the line", art: "fleet_boss_tithe", ammo: "explosive", boss: true,
        hp: 490, guns: 8, accuracy: 0.69, rake: 0.16,
        flavor: "It takes a tenth of everything that passes. The tenth is not negotiable and neither is the price." },

    { rank: 11, name: "Kraken's Dowry", cls: "Razee", art: "fleet_razee", ammo: "chain",
        hp: 560, guns: 8, accuracy: 0.71, rake: 0.15,
        flavor: "Cut down a deck for speed and still heavier than anything you have met." },
    { rank: 12, name: "Pale Lantern", cls: "Ghost brig", art: "fleet_ghost", ammo: "grape",
        hp: 620, guns: 8, accuracy: 0.72, rake: 0.16,
        flavor: "No crew answers the hail. The guns run out anyway." },
    { rank: 13, name: "Cannonade", cls: "Bomb vessel", art: "fleet_bomb", ammo: "explosive",
        hp: 690, guns: 8, accuracy: 0.7, rake: 0.18,
        flavor: "Built around a mortar and a complete disregard for its own timbers." },
    { rank: 14, name: "The Long Arrears", cls: "Man-o'-war", art: "fleet_manowar", ammo: "round",
        hp: 740, guns: 9, accuracy: 0.77, rake: 0.2,
        flavor: "Three decks of guns and a purser who writes down every ball he spends on you." },
    { rank: 15, name: "Admiral Vane's Sovereign", cls: "Flagship", art: "fleet_boss_sovereign", ammo: "explosive", boss: true,
        hp: 820, guns: 9, accuracy: 0.75, rake: 0.22,
        flavor: "The reason the fleet has a name. Vane has never had to fire a second broadside." },
];

import { fleetDeck } from "@/lib/marketplace/deck-lines.js";
import { hullGrade } from "@/lib/marketplace/ship-battle.js";

export const MAX_FLEET_RANK = FLEET.length;
// ── WHAT RANK IS THAT SHIP? ──────────────────────────────────────────────────────────────────────────────────
// A member's ship is not a rung on the ladder, but it is comparable to one: it has guns and a hull. Matching it
// to the nearest fleet rank lets a RAID pay out of the same reward table as everything else, so there is one
// reward design in the game rather than two that have to be balanced against each other forever.
//
// Matched on HULL alone, and that is deliberate. It used to weigh guns too, which stopped working the moment
// guns became something you buy rather than something you get: every member has one gun until they spend on
// the Cannons track, so every member collapsed to rank 1 and a 208-hull ship paid like a fishing boat.
//
// Hull is also the honest axis. It is the dimension a player actually grows — boat level IS hull now — so
// matching on it makes the tier rise with investment, monotonically: boat 1 ranks 1, boat 25 ranks 5, a
// maxed boat and hull track ranks 10. Guns still decide the FIGHT; they just do not decide how big you are.
export function fleetRankForShip({ hp = 140 } = {}) {
    let best = FLEET[0], bestGap = Infinity;
    for (const f of FLEET) {
        const gap = Math.abs(f.hp - hp);
        if (gap < bestGap) { bestGap = gap; best = f; }
    }
    return best.rank;
}

export const fleetArt = (ship) => (ship?.art ? `/images/fleet/${ship.art}.png` : null);
// Where this hull's deck sits, so its captain stands ON the boat instead of above it. One number per ship
// because one global percentage cannot fit fifteen different hulls — see deck-lines.js.
export const fleetDeckOf = (ship) => fleetDeck(ship?.art);
// The ship's CAPTAIN, who stands on its deck the way your hero stands on yours. A fleet battle against an
// empty hull is scenery you shot at; a ship with somebody on it is an opponent you beat.
// (scripts/gen-fleet-captains.mjs — drawn facing right, because the scene mirrors the enemy's crew.)
export const fleetCaptain = (ship) => (ship?.art ? `/images/fleet/crew/${ship.art}.png` : null);
export const fleetShip = (rank) => FLEET.find((f) => f.rank === Number(rank)) || null;

// ── WHAT SINKING ONE PAYS ────────────────────────────────────────────────────────────────────────────────────
// The old raid paid gold and a 0.5% chance to copy an item, which is a slot machine attached to a fight. This
// pays a HAND of things, and most of them are worth something in another part of the game — forge parts to
// enhance with, treasure fragments toward a chest, seeds for the farm — so an evening of ship battles moves
// whatever else you are working on. Doubloons are the only currency the fleet mints, and the Quartermaster is
// the only place they spend.
//
// Every rank pays doubloons and fragments. Bosses add a chest and a bigger purse. The FIRST time you sink a
// rank pays a clear bonus over re-fighting it, so climbing beats farming rank 1 forever.
export function fleetReward(rank, { first = false } = {}) {
    const ship = fleetShip(rank);
    if (!ship) return null;
    const r = ship.rank;
    const boss = Boolean(ship.boss);
    const mult = first ? 1 : 0.4; // re-fights pay 40% — worth doing, never the best way up
    const round = (n) => Math.max(1, Math.round(n * mult));
    return {
        doubloons: round(6 + r * 2 + (boss ? 18 : 0)),
        // GOLD CAME DOWN HARD. It was 40 + 26/rank + 260 on a boss, so the flagship paid 690 a sinking on top
        // of everything else in this table — the fight was worth more than what it was for.
        gold: round(25 + r * 11 + (boss ? 110 : 0)),
        xp: round(18 + r * 7 + (boss ? 80 : 0)),
        // Sailing's own chest currency, and the TIER is what scales — not the pile. It used to climb to nine
        // mythic fragments a sinking, which is a chest and a half from one fight. Three at the top, and the
        // rung decides what KIND of jar it fills rather than how fast.
        fragments: round(r >= 9 ? 3 : r >= 5 ? 2 : 1),
        fragTier: r >= 13 ? "mythic" : r >= 9 ? "gold" : r >= 5 ? "iron" : "wooden",
        // Forge parts, tiered by how far down the fleet you are. The Forge is where people want for materials.
        parts: r >= 3 ? { tier: Math.min(5, 1 + Math.floor(r / 4)), n: round(1 + Math.floor(r / 5) + (boss ? 2 : 0)) } : null,
        // NO CHEST. Bosses used to drop one outright, which is the same reward twice: fragments ARE the chest
        // currency, so a boss paid you a chest and most of the makings of a second one. Forge it yourself.
        chest: null,
        // A seed for the farm from the mid fleet on — small, but it lands somewhere else in the game.
        seed: r >= 6 && first ? true : false,
        // PLUNDER OFF THEIR DECK. A beaten crew should occasionally leave something behind, and it is the one
        // reward that makes a sinking feel like a boarding rather than a payout. Deliberately uncommon and
        // deliberately weighted DOWN: the rank sets the ceiling and the odds, but common is always the most
        // likely roll, so this stays a nice surprise rather than a gear faucet that outruns the Forge.
        loot: { chance: Math.min(0.34, 0.06 + r * 0.018) * (first ? 1 : 0.5), maxRank: r, boss },
        first,
        boss,
    };
}

// The fleet as the client renders it: everything up to and including the next unfought rank, so the ladder is
// visible ahead of you (an unbeaten rung names what you are climbing toward) and nothing past the horizon.
export function fleetView(depth = 0) {
    const next = Math.min(MAX_FLEET_RANK, depth + 1);
    // Two ranks PAST the one you can fight, shown locked. The list is merged with member rivals now and sorted
    // by difficulty — without the locked rungs the ladder just stopped, and a rival ranked above your depth
    // appeared to be the next thing in a fleet that had apparently run out. Seeing what is behind the door is
    // also the reason to keep climbing.
    const show = Math.min(MAX_FLEET_RANK, next + 2);
    return FLEET.filter((f) => f.rank <= show).map((f) => ({
        rank: f.rank, name: f.name, cls: f.cls, art: fleetArt(f), boss: Boolean(f.boss), flavor: f.flavor,
        // The captain, so the picker can show the person on their deck rather than an empty hull.
        crew: fleetCaptain(f),
        guns: f.guns, hp: f.hp, ammo: f.ammo, hullGrade: hullGrade(f.hp),
        beaten: f.rank <= depth,
        current: f.rank === next && f.rank > depth,
        locked: f.rank > next,
        reward: fleetReward(f.rank, { first: f.rank > depth }),
    }));
}
