// ── THE PIRATE FLEET ─────────────────────────────────────────────────────────────────────────────────────────
// The ladder ship battles are actually about. Raiding another member is a side action — it depends on who
// happens to be online, and beating a beginner pays what beating a rival pays — so the PROGRESSION is a fixed
// fleet of designed enemies you fight in order. Rank 1 is a fishing cutter that has taken up piracy; rank 15 is
// a flagship. Your `fleet_depth` is the highest rank you have sunk, and the next sortie is depth + 1.
//
// Losing costs you nothing but the sortie. A ladder that takes rungs away when you slip is a ladder people stop
// climbing, and this game does not punish (see the engagement notes) — the cost of losing is that you did not
// win yet.
//
// Every fifth rank is a NAMED ship: a wall with a captain, a story line, and a reward worth the wall. They are
// where the chest and the gear come from, so the fleet feeds the rest of the game rather than only itself.
//
// `art` is the sprite's file key; the hulls live in /public/images/fleet and are generated by
// scripts/gen-fleet-ships.mjs. They are drawn facing LEFT on purpose — the enemy stands on the right of the
// battle stage, and mirroring a hull in CSS mirrors its lighting with it.

export const FLEET = [
    { rank: 1, name: "Gull's Folly", cls: "Fishing cutter", art: "fleet_cutter", ammo: "round",
        hp: 105, guns: 2, accuracy: 0.52, rake: 0.05, armor: 0.0,
        flavor: "A fishing boat with two stolen guns lashed to the deck. It should not be out here." },
    { rank: 2, name: "Wet Powder", cls: "Smuggler's sloop", art: "fleet_sloop", ammo: "round",
        hp: 145, guns: 3, accuracy: 0.55, rake: 0.06, armor: 0.02,
        flavor: "Fast, low, and carrying more brandy than shot." },
    { rank: 3, name: "The Cormorant", cls: "Coastal lugger", art: "fleet_lugger", ammo: "grape",
        hp: 185, guns: 4, accuracy: 0.57, rake: 0.07, armor: 0.03,
        flavor: "Loads grape and sweeps decks. Stay behind your bulwarks." },
    { rank: 4, name: "Iron Nettle", cls: "Gun brig", art: "fleet_brig", ammo: "round",
        hp: 230, guns: 5, accuracy: 0.59, rake: 0.08, armor: 0.05,
        flavor: "Plated at the waterline with whatever the last wreck was carrying." },
    { rank: 5, name: "Salt Meg's Revenge", cls: "Brigantine", art: "fleet_boss_revenge", ammo: "chain", boss: true,
        hp: 305, guns: 8, accuracy: 0.62, rake: 0.11, armor: 0.08,
        flavor: "Meg takes your rigging first and your cargo at her leisure. Nobody has out-run her twice." },

    { rank: 6, name: "The Hollow Tide", cls: "Schooner", art: "fleet_schooner", ammo: "round",
        hp: 330, guns: 8, accuracy: 0.61, rake: 0.1, armor: 0.1,
        flavor: "Crewed thin and sailed hard. It will trade with you all afternoon." },
    { rank: 7, name: "Bitterhold", cls: "Corvette", art: "fleet_corvette", ammo: "explosive",
        hp: 385, guns: 7, accuracy: 0.63, rake: 0.12, armor: 0.12,
        flavor: "Fires shells. Half go wide; the half that don't set your deck alight." },
    { rank: 8, name: "Widow's Wage", cls: "Privateer frigate", art: "fleet_frigate", ammo: "grape",
        hp: 445, guns: 10, accuracy: 0.65, rake: 0.13, armor: 0.14,
        flavor: "A letter of marque from a country that no longer exists, and no intention of checking." },
    { rank: 9, name: "The Grinding Reef", cls: "Heavy frigate", art: "fleet_heavy", ammo: "round",
        hp: 510, guns: 11, accuracy: 0.67, rake: 0.13, armor: 0.17,
        flavor: "Slow, armoured, and entirely willing to sit there and out-last you." },
    { rank: 10, name: "The Black Tithe", cls: "Ship of the line", art: "fleet_boss_tithe", ammo: "explosive", boss: true,
        hp: 630, guns: 10, accuracy: 0.69, rake: 0.16, armor: 0.19,
        flavor: "It takes a tenth of everything that passes. The tenth is not negotiable and neither is the price." },

    { rank: 11, name: "Kraken's Dowry", cls: "Razee", art: "fleet_razee", ammo: "chain",
        hp: 730, guns: 16, accuracy: 0.71, rake: 0.15, armor: 0.23,
        flavor: "Cut down a deck for speed and still heavier than anything you have met." },
    { rank: 12, name: "Pale Lantern", cls: "Ghost brig", art: "fleet_ghost", ammo: "grape",
        hp: 780, guns: 15, accuracy: 0.72, rake: 0.16, armor: 0.25,
        flavor: "No crew answers the hail. The guns run out anyway." },
    { rank: 13, name: "Cannonade", cls: "Bomb vessel", art: "fleet_bomb", ammo: "explosive",
        hp: 840, guns: 13, accuracy: 0.7, rake: 0.18, armor: 0.27,
        flavor: "Built around a mortar and a complete disregard for its own timbers." },
    { rank: 14, name: "The Long Arrears", cls: "Man-o'-war", art: "fleet_manowar", ammo: "round",
        hp: 945, guns: 17, accuracy: 0.77, rake: 0.2, armor: 0.29,
        flavor: "Three decks of guns and a purser who writes down every ball he spends on you." },
    { rank: 15, name: "Admiral Vane's Sovereign", cls: "Flagship", art: "fleet_boss_sovereign", ammo: "explosive", boss: true,
        hp: 1000, guns: 14, accuracy: 0.75, rake: 0.22, armor: 0.28,
        flavor: "The reason the fleet has a name. Vane has never had to fire a second broadside." },
];

export const MAX_FLEET_RANK = FLEET.length;
// ── WHAT RANK IS THAT SHIP? ──────────────────────────────────────────────────────────────────────────────────
// A member's ship is not a rung on the ladder, but it is comparable to one: it has guns and a hull. Matching it
// to the nearest fleet rank lets a RAID pay out of the same reward table as everything else, so there is one
// reward design in the game rather than two that have to be balanced against each other forever.
//
// Compared on both dimensions because either alone lies — a gunboat with no hull and a fat trader with two
// cannons are not the same problem, and averaging them separately would rank both as "middling".
export function fleetRankForShip({ guns = 4, hp = 140 } = {}) {
    let best = FLEET[0], bestGap = Infinity;
    for (const f of FLEET) {
        const gap = Math.abs(f.guns - guns) / 4 + Math.abs(f.hp - hp) / 200;
        if (gap < bestGap) { bestGap = gap; best = f; }
    }
    return best.rank;
}

export const fleetArt = (ship) => (ship?.art ? `/images/fleet/${ship.art}.png` : null);
// The ship's CAPTAIN, who stands on its deck the way your hero stands on yours. A fleet battle against an
// empty hull is scenery you shot at; a ship with somebody on it is an opponent you beat.
// (scripts/gen-fleet-captains.mjs — drawn facing right, because the scene mirrors the enemy's crew.)
export const fleetCaptain = (ship) => (ship?.art ? `/images/fleet/crew/${ship.art}.png` : null);
export const fleetShip = (rank) => FLEET.find((f) => f.rank === Number(rank)) || null;

// ── WHAT SINKING ONE PAYS ────────────────────────────────────────────────────────────────────────────────────
// The old raid paid gold and a 0.5% chance to copy an item, which is a slot machine attached to a fight. This
// pays a HAND of things, and most of them are worth something in another part of the game — forge parts to
// enhance with, treasure fragments toward a chest, seeds for the farm — so an evening of ship battles moves
// whatever else you are working on. Doubloons are the only currency the fleet mints, and the Quartermaster is
// the only place they spend.
//
// Every rank pays doubloons and fragments. Bosses add a chest and a bigger purse. The FIRST time you sink a
// rank pays a clear bonus over re-fighting it, so climbing beats farming rank 1 forever.
export function fleetReward(rank, { first = false } = {}) {
    const ship = fleetShip(rank);
    if (!ship) return null;
    const r = ship.rank;
    const boss = Boolean(ship.boss);
    const mult = first ? 1 : 0.4; // re-fights pay 40% — worth doing, never the best way up
    const round = (n) => Math.max(1, Math.round(n * mult));
    return {
        doubloons: round(6 + r * 2 + (boss ? 18 : 0)),
        gold: round(40 + r * 26 + (boss ? 260 : 0)),
        xp: round(18 + r * 7 + (boss ? 80 : 0)),
        // Sailing's own chest currency — a battle now feeds the dig economy it sits next to.
        fragments: round(1 + Math.floor(r / 3) + (boss ? 3 : 0)),
        // Forge parts, tiered by how far down the fleet you are. The Forge is where people want for materials.
        parts: r >= 3 ? { tier: Math.min(5, 1 + Math.floor(r / 4)), n: round(1 + Math.floor(r / 5) + (boss ? 2 : 0)) } : null,
        // Bosses drop a chest, and the last two drop a good one. This is the fleet's tie into gear.
        chest: boss ? (r >= 15 ? "mythic" : r >= 10 ? "gold" : "iron") : null,
        // A seed for the farm from the mid fleet on — small, but it lands somewhere else in the game.
        seed: r >= 6 && first ? true : false,
        first,
        boss,
    };
}

// The fleet as the client renders it: everything up to and including the next unfought rank, so the ladder is
// visible ahead of you (an unbeaten rung names what you are climbing toward) and nothing past the horizon.
export function fleetView(depth = 0) {
    const next = Math.min(MAX_FLEET_RANK, depth + 1);
    return FLEET.filter((f) => f.rank <= next).map((f) => ({
        rank: f.rank, name: f.name, cls: f.cls, art: fleetArt(f), boss: Boolean(f.boss), flavor: f.flavor,
        guns: f.guns, hp: f.hp, ammo: f.ammo,
        beaten: f.rank <= depth,
        current: f.rank === next && f.rank > depth,
        reward: fleetReward(f.rank, { first: f.rank > depth }),
    }));
}
