// ── THE PIRATE FLEET ─────────────────────────────────────────────────────────────────────────────────────────
// The ladder ship battles are actually about. Raiding another member is a side action — it depends on who
// happens to be online, and beating a beginner pays what beating a rival pays — so the PROGRESSION is a fixed
// fleet of designed enemies you fight in order. Rank 1 is a fishing cutter that has taken up piracy; rank 15 is
// a flagship. Your `fleet_depth` is the highest rank you have sunk, and the next sortie is depth + 1.
//
// Losing costs you nothing but the sortie. A ladder that takes rungs away when you slip is a ladder people stop
// climbing, and this game does not punish (see the engagement notes) — the cost of losing is that you did not
// win yet.
//
// Every fifth rank is a NAMED ship: a wall with a captain, a story line, and a reward worth the wall. They are
// where the chest and the gear come from, so the fleet feeds the rest of the game rather than only itself.
//
// `art` is the sprite's file key; the hulls live in /public/images/fleet and are generated by
// scripts/gen-fleet-ships.mjs. They are drawn facing LEFT on purpose — the enemy stands on the right of the
// battle stage, and mirroring a hull in CSS mirrors its lighting with it.

export const FLEET = [
    { rank: 1, name: "Gull's Folly", cls: "Fishing cutter", art: "fleet_cutter", ammo: "round",
        hits: 6, hp: 78, guns: 2, accuracy: 0.52, rake: 0.05,
        flavor: "A fishing boat with two stolen guns lashed to the deck. It should not be out here." },
    { rank: 2, name: "Wet Powder", cls: "Smuggler's sloop", art: "fleet_sloop", ammo: "round",
        hits: 7, hp: 112, guns: 3, accuracy: 0.55, rake: 0.06,
        flavor: "Fast, low, and carrying more brandy than shot." },
    { rank: 3, name: "The Cormorant", cls: "Coastal lugger", art: "fleet_lugger", ammo: "grape",
        hits: 8, hp: 155, guns: 3, accuracy: 0.57, rake: 0.07,
        flavor: "Loads grape and sweeps decks. Stay behind your bulwarks." },
    { rank: 4, name: "Iron Nettle", cls: "Gun brig", art: "fleet_brig", ammo: "round",
        hits: 9, hp: 230, guns: 5, accuracy: 0.59, rake: 0.08,
        flavor: "Plated at the waterline with whatever the last wreck was carrying." },
    { rank: 5, name: "Salt Meg's Revenge", cls: "Brigantine", art: "fleet_boss_revenge", ammo: "chain", boss: true,
        hits: 10, hp: 280, guns: 6, accuracy: 0.62, rake: 0.11,
        flavor: "Meg takes your rigging first and your cargo at her leisure. Nobody has out-run her twice." },

    { rank: 6, name: "The Hollow Tide", cls: "Schooner", art: "fleet_schooner", ammo: "round",
        hits: 11, hp: 315, guns: 6, accuracy: 0.61, rake: 0.1,
        flavor: "Crewed thin and sailed hard. It will trade with you all afternoon." },
    { rank: 7, name: "Bitterhold", cls: "Corvette", art: "fleet_corvette", ammo: "explosive",
        hits: 12, hp: 355, guns: 7, accuracy: 0.63, rake: 0.12,
        flavor: "Fires shells. Half go wide; the half that don't set your deck alight." },
    { rank: 8, name: "Widow's Wage", cls: "Privateer frigate", art: "fleet_frigate", ammo: "grape",
        hits: 13, hp: 400, guns: 7, accuracy: 0.65, rake: 0.13,
        flavor: "A letter of marque from a country that no longer exists, and no intention of checking." },
    { rank: 9, name: "The Grinding Reef", cls: "Heavy frigate", art: "fleet_heavy", ammo: "round",
        hits: 14, hp: 440, guns: 8, accuracy: 0.67, rake: 0.13,
        flavor: "Slow, heavy, and entirely willing to sit there and out-last you." },
    { rank: 10, name: "The Black Tithe", cls: "Ship of the line", art: "fleet_boss_tithe", ammo: "explosive", boss: true,
        hits: 15, hp: 490, guns: 8, accuracy: 0.69, rake: 0.16,
        flavor: "It takes a tenth of everything that passes. The tenth is not negotiable and neither is the price." },

    { rank: 11, name: "Kraken's Dowry", cls: "Razee", art: "fleet_razee", ammo: "chain",
        hits: 16, hp: 560, guns: 8, accuracy: 0.71, rake: 0.15,
        flavor: "Cut down a deck for speed and still heavier than anything you have met." },
    { rank: 12, name: "Pale Lantern", cls: "Ghost brig", art: "fleet_ghost", ammo: "grape",
        hits: 17, hp: 620, guns: 8, accuracy: 0.72, rake: 0.16,
        flavor: "No crew answers the hail. The guns run out anyway." },
    { rank: 13, name: "Cannonade", cls: "Bomb vessel", art: "fleet_bomb", ammo: "explosive",
        hits: 18, hp: 690, guns: 8, accuracy: 0.7, rake: 0.18,
        flavor: "Built around a mortar and a complete disregard for its own timbers." },
    { rank: 14, name: "The Long Arrears", cls: "Man-o'-war", art: "fleet_manowar", ammo: "round",
        hits: 19, hp: 740, guns: 9, accuracy: 0.77, rake: 0.2,
        flavor: "Three decks of guns and a purser who writes down every ball he spends on you." },
    { rank: 15, name: "Admiral Vane's Sovereign", cls: "Flagship", art: "fleet_boss_sovereign", ammo: "explosive", boss: true,
        hits: 20, hp: 820, guns: 9, accuracy: 0.75, rake: 0.22,
        flavor: "The reason the fleet has a name. Vane has never had to fire a second broadside." },

    // ── ⚠️ PAST THE FLAGSHIP, BECAUSE SEVEN CAPTAINS HAD FINISHED THE LADDER ────────────────
    // Luke: "I havent lost a sea raid in weeks. looking for an actual challenge."
    // Measured before writing a line of this. The Den has fought 828 fleet battles and won 768 of them —
    // 93%. Seven captains sit at depth 15 with nothing above them, and two of them have never lost at all:
    // Kaishiern 51-0, Luke 44-0. It is not a tuning problem and it is not luck. The ladder is finished.
    //
    // ⚠️ AND IT COULD NOT HAVE BEEN EXTENDED WITHOUT THIS: foePlanks reads `foe.hits` and falls back to
    // clamp(5 + rank, 5, 22). Not one ship in the fleet had a `hits`, so every hull was that fallback — and
    // it CAPS AT 22. Ranks 16, 17 and 18 would each have had a 22-plank hull and rank 40 would have had the
    // same 22 as rank 17. Twenty-five new ships, twenty-three of them identical where it counts. The `hp`
    // field in this table is decorative and has always been (see the note by foePlanks); `hits` is the hull
    // the fight actually counts. Every rank now says its own, including the original fifteen — which are
    // written at exactly the number the fallback was already giving them, so nothing changes for anybody
    // who is mid-ladder.
    //
    // The captain's own ceiling is fixed and low: 7 guns, 22 planks, 96% accuracy, all of them maxed by the
    // people asking for this. So the climb past 15 is carried by HULL and GUNS rather than by accuracy,
    // which is nearly capped by rank 20 and has nowhere to go.
    //
    // ⚠️ THESE NUMBERS ARE A FIRST CUT AND MUST BE MEASURED AGAINST REAL BOUTS. matchupOdds already says
    // rank 15 is a 44% fight and the Den wins it every time — the model does not see aiming, ammo or the
    // loadout, so it cannot be trusted to price a rung. Watch the win rate at 16-20 for a week and steepen
    // or flatten from what actually happens, not from the model.

    { rank: 16, name: "Revenue Cutter Thorn", cls: "Revenue cutter", art: "fleet_thorn", ammo: "round",
        hits: 22, hp: 924, guns: 10, accuracy: 0.76, rake: 0.23,
        flavor: "Flies a flag you recognise. That is worse, not better." },
    { rank: 17, name: "The Assize", cls: "Patrol sloop", art: "fleet_assize", ammo: "grape",
        hits: 24, hp: 1008, guns: 10, accuracy: 0.77, rake: 0.24,
        flavor: "Carries a magistrate and a rope, and has never needed the magistrate." },
    { rank: 18, name: "Hammerfall", cls: "Bomb ketch", art: "fleet_hammerfall", ammo: "explosive",
        hits: 26, hp: 1092, guns: 11, accuracy: 0.77, rake: 0.26,
        flavor: "It does not chase. It ranges you, and then it is simply over." },
    { rank: 19, name: "Cold Assurance", cls: "Escort frigate", art: "fleet_assurance", ammo: "chain",
        hits: 28, hp: 1176, guns: 11, accuracy: 0.78, rake: 0.26,
        flavor: "Insures the convoy behind it. It settles claims with the guns." },
    { rank: 20, name: "Commodore Ash", cls: "Squadron flagship", art: "fleet_boss_ash", ammo: "explosive", boss: true,
        hits: 31, hp: 1302, guns: 12, accuracy: 0.8, rake: 0.3,
        flavor: "He was given a fleet to end piracy and has decided to end sailors instead." },
    { rank: 21, name: "The Long Blockade", cls: "Line frigate", art: "fleet_blockade", ammo: "round",
        hits: 33, hp: 1386, guns: 12, accuracy: 0.8, rake: 0.28,
        flavor: "It has sat off this coast for nine years. It is not in a hurry now." },
    { rank: 22, name: "Sixty-Four", cls: "Third rate", art: "fleet_sixtyfour", ammo: "round",
        hits: 35, hp: 1470, guns: 13, accuracy: 0.81, rake: 0.29,
        flavor: "Sixty-four guns and a name nobody bothered to improve on." },
    { rank: 23, name: "The Iron Verdict", cls: "Ironclad ram", art: "fleet_verdict", ammo: "chain",
        hits: 38, hp: 1596, guns: 13, accuracy: 0.81, rake: 0.31,
        flavor: "Plated stem to stern. Shot comes off it like rain off a roof." },
    { rank: 24, name: "Gallowglass", cls: "Mercenary razee", art: "fleet_gallowglass", ammo: "grape",
        hits: 40, hp: 1680, guns: 14, accuracy: 0.82, rake: 0.32,
        flavor: "Fights for whoever paid last. Today that was not you." },
    { rank: 25, name: "Admiral Vane's Reprisal", cls: "Rebuilt flagship", art: "fleet_boss_reprisal", ammo: "explosive", boss: true,
        hits: 44, hp: 1848, guns: 15, accuracy: 0.84, rake: 0.35,
        flavor: "You sank the Sovereign. He has had a year and a grudge and a shipyard." },
    { rank: 26, name: "The Salt Choir", cls: "Drowned brig", art: "fleet_choir", ammo: "chain",
        hits: 46, hp: 1932, guns: 15, accuracy: 0.83, rake: 0.32,
        flavor: "You can hear the crew. You should not be able to hear the crew." },
    { rank: 27, name: "Wreck of the Marigold", cls: "Risen wreck", art: "fleet_marigold", ammo: "round",
        hits: 48, hp: 2016, guns: 15, accuracy: 0.83, rake: 0.33,
        flavor: "It went down with all hands eighty years ago and has not stopped sailing." },
    { rank: 28, name: "Barnacle Court", cls: "Coral hulk", art: "fleet_court", ammo: "grape",
        hits: 51, hp: 2142, guns: 16, accuracy: 0.84, rake: 0.34,
        flavor: "More reef than ship now, and the reef has opinions." },
    { rank: 29, name: "The Lamprey", cls: "Boarding hulk", art: "fleet_lamprey", ammo: "chain",
        hits: 53, hp: 2226, guns: 16, accuracy: 0.84, rake: 0.35,
        flavor: "It does not want to sink you. It wants to be alongside." },
    { rank: 30, name: "The Tide Marshal", cls: "Leviathan-drawn barge", art: "fleet_boss_marshal", ammo: "explosive", boss: true,
        hits: 57, hp: 2394, guns: 17, accuracy: 0.86, rake: 0.38,
        flavor: "Something under the water is pulling it, and it is pulling it toward you." },
    { rank: 31, name: "Gravemouth", cls: "Whaler, converted", art: "fleet_gravemouth", ammo: "explosive",
        hits: 59, hp: 2478, guns: 17, accuracy: 0.85, rake: 0.36,
        flavor: "Built to kill something bigger than a ship. It has kept the habit." },
    { rank: 32, name: "The Nine Widows", cls: "Ghost squadron", art: "fleet_widows", ammo: "grape",
        hits: 62, hp: 2604, guns: 17, accuracy: 0.85, rake: 0.37,
        flavor: "Nine sets of running lights. There is only ever one hull." },
    { rank: 33, name: "Pressgang", cls: "Slaver hulk", art: "fleet_pressgang", ammo: "chain",
        hits: 64, hp: 2688, guns: 18, accuracy: 0.86, rake: 0.38,
        flavor: "It is short of crew. It has been short of crew for a very long time." },
    { rank: 34, name: "The Undertow", cls: "Storm cutter", art: "fleet_undertow", ammo: "round",
        hits: 67, hp: 2814, guns: 18, accuracy: 0.86, rake: 0.38,
        flavor: "It brings its own weather and it does not sail in anybody else's." },
    { rank: 35, name: "Mother Fathom", cls: "Abyssal dreadnought", art: "fleet_boss_fathom", ammo: "explosive", boss: true,
        hits: 72, hp: 3024, guns: 19, accuracy: 0.88, rake: 0.42,
        flavor: "She has been down there since before anybody thought to name the sea." },
    { rank: 36, name: "The Long Reckoning", cls: "Hulk of the fleet", art: "fleet_reckoning", ammo: "round",
        hits: 75, hp: 3150, guns: 19, accuracy: 0.87, rake: 0.4,
        flavor: "Every ship you have sunk, welded into one and still floating." },
    { rank: 37, name: "Cartographer's Regret", cls: "Charting vessel", art: "fleet_regret", ammo: "grape",
        hits: 78, hp: 3276, guns: 20, accuracy: 0.88, rake: 0.41,
        flavor: "It maps the water you are standing on. You are on the chart already." },
    { rank: 38, name: "The Unbroken Line", cls: "Battle line, entire", art: "fleet_line", ammo: "chain",
        hits: 82, hp: 3444, guns: 20, accuracy: 0.88, rake: 0.42,
        flavor: "Not a ship. Eleven of them, and they have done this before." },
    { rank: 39, name: "Hull Seventeen", cls: "Nameless prototype", art: "fleet_seventeen", ammo: "explosive",
        hits: 86, hp: 3612, guns: 21, accuracy: 0.89, rake: 0.44,
        flavor: "No flag, no name, no crew on deck. The yard that built it burned down after." },
    { rank: 40, name: "The Last Harbour", cls: "The thing at the bottom", art: "fleet_boss_harbour", ammo: "explosive", boss: true,
        hits: 95, hp: 3990, guns: 22, accuracy: 0.9, rake: 0.48,
        flavor: "Everything that ever sank is moored here. It is not a place. It is waiting." },
];

import { fleetDeck } from "@/lib/marketplace/deck-lines.js";
import { hullGrade } from "@/lib/marketplace/ship-battle.js";

export const MAX_FLEET_RANK = FLEET.length;
// ── WHAT RANK IS THAT SHIP? ──────────────────────────────────────────────────────────────────────────────────
// A member's ship is not a rung on the ladder, but it is comparable to one: it has guns and a hull. Matching it
// to the nearest fleet rank lets a RAID pay out of the same reward table as everything else, so there is one
// reward design in the game rather than two that have to be balanced against each other forever.
//
// Matched on HULL alone, and that is deliberate. It used to weigh guns too, which stopped working the moment
// guns became something you buy rather than something you get: every member has one gun until they spend on
// the Cannons track, so every member collapsed to rank 1 and a 208-hull ship paid like a fishing boat.
//
// Hull is also the honest axis. It is the dimension a player actually grows — boat level IS hull now — so
// matching on it makes the tier rise with investment, monotonically: boat 1 ranks 1, boat 25 ranks 5, a
// maxed boat and hull track ranks 10. Guns still decide the FIGHT; they just do not decide how big you are.
export function fleetRankForShip({ hp = 140 } = {}) {
    let best = FLEET[0], bestGap = Infinity;
    for (const f of FLEET) {
        const gap = Math.abs(f.hp - hp);
        if (gap < bestGap) { bestGap = gap; best = f; }
    }
    return best.rank;
}

export const fleetArt = (ship) => (ship?.art ? `/images/fleet/${ship.art}.png` : null);
// Where this hull's deck sits, so its captain stands ON the boat instead of above it. One number per ship
// because one global percentage cannot fit fifteen different hulls — see deck-lines.js.
export const fleetDeckOf = (ship) => fleetDeck(ship?.art);
// The ship's CAPTAIN, who stands on its deck the way your hero stands on yours. A fleet battle against an
// empty hull is scenery you shot at; a ship with somebody on it is an opponent you beat.
// (scripts/gen-fleet-captains.mjs — drawn facing right, because the scene mirrors the enemy's crew.)
export const fleetCaptain = (ship) => (ship?.art ? `/images/fleet/crew/${ship.art}.png` : null);
export const fleetShip = (rank) => FLEET.find((f) => f.rank === Number(rank)) || null;

// ── WHAT SINKING ONE PAYS ────────────────────────────────────────────────────────────────────────────────────
// The old raid paid gold and a 0.5% chance to copy an item, which is a slot machine attached to a fight. This
// pays a HAND of things, and most of them are worth something in another part of the game — forge parts to
// enhance with, treasure fragments toward a chest, seeds for the farm — so an evening of ship battles moves
// whatever else you are working on. Doubloons are the only currency the fleet mints, and the Quartermaster is
// the only place they spend.
//
// Every rank pays doubloons and fragments. Bosses add a chest and a bigger purse. The FIRST time you sink a
// rank pays a clear bonus over re-fighting it, so climbing beats farming rank 1 forever.
// ⚠️ `boss` MAY BE OVERRIDDEN, BECAUSE A MEMBER'S BOAT IS NOT A MAN-O'-WAR. A member raid matches the rival's
// hull to the nearest fleet rank by HP (fleetRankForShip), and ranks 5, 10 and 15 are BOSSES — so a member
// whose boat happened to sit near a boss hull paid out the boss bonus: +18 doubloons, +110 gold, +80 XP for
// beating somebody's sloop. It is visible as a sawtooth in the payout curve, where rank 5 pays more than
// rank 8 and rank 10 more than rank 13. Member-vs-member passes `boss: false` on BOTH sides — the raider's
// win and the defender's repel — because the same hull cannot be a boss for one of them and not the other.
export function fleetReward(rank, { first = false, boss: bossOverride = null } = {}) {
    const ship = fleetShip(rank);
    if (!ship) return null;
    // ── ⚠️ THE PAYOUT DOES NOT CLIMB AS FAST AS THE LADDER DOES ───────────────────────
    // Everything below is linear in the rank, which was fine while the ladder stopped at 15. Run straight
    // out to 40 it triples the gold a top captain takes off the sea: a rank-40 re-fight would pay 230 where
    // rank 15 pays 76, five sorties a day, on the seven people who already have everything.
    //
    // So the rank the REWARD is worked out from grows at about a third of the rate past 15. Rank 40 pays
    // like rank 24 — a real lift over the old top rung, and nothing like a tripling. The reason to climb
    // past the flagship is the climb; the fight is the reward and the ladder says so.
    // Nothing at or below 15 moves by a single coin: `payRank` is exactly `r` there.
    const r = Math.min(ship.rank, 15 + (ship.rank - 15) * 0.35);
    const boss = bossOverride === null ? Boolean(ship.boss) : Boolean(bossOverride);
    const mult = first ? 1 : 0.4; // re-fights pay 40% — worth doing, never the best way up
    const round = (n) => Math.max(1, Math.round(n * mult));
    return {
        doubloons: round(6 + r * 2 + (boss ? 18 : 0)),
        // GOLD CAME DOWN HARD. It was 40 + 26/rank + 260 on a boss, so the flagship paid 690 a sinking on top
        // of everything else in this table — the fight was worth more than what it was for.
        gold: round(25 + r * 11 + (boss ? 110 : 0)),
        xp: round(18 + r * 7 + (boss ? 80 : 0)),
        // Sailing's own chest currency, and the TIER is what scales — not the pile. It used to climb to nine
        // mythic fragments a sinking, which is a chest and a half from one fight. Three at the top, and the
        // rung decides what KIND of jar it fills rather than how fast.
        fragments: round(r >= 9 ? 3 : r >= 5 ? 2 : 1),
        fragTier: r >= 13 ? "mythic" : r >= 9 ? "gold" : r >= 5 ? "iron" : "wooden",
        // Forge parts, tiered by how far down the fleet you are. The Forge is where people want for materials.
        parts: r >= 3 ? { tier: Math.min(5, 1 + Math.floor(r / 4)), n: round(1 + Math.floor(r / 5) + (boss ? 2 : 0)) } : null,
        // NO CHEST. Bosses used to drop one outright, which is the same reward twice: fragments ARE the chest
        // currency, so a boss paid you a chest and most of the makings of a second one. Forge it yourself.
        chest: null,
        // A seed for the farm from the mid fleet on — small, but it lands somewhere else in the game.
        seed: r >= 6 && first ? true : false,
        // PLUNDER OFF THEIR DECK. A beaten crew should occasionally leave something behind, and it is the one
        // reward that makes a sinking feel like a boarding rather than a payout. Deliberately uncommon and
        // deliberately weighted DOWN: the rank sets the ceiling and the odds, but common is always the most
        // likely roll, so this stays a nice surprise rather than a gear faucet that outruns the Forge.
        loot: { chance: Math.min(0.34, 0.06 + r * 0.018) * (first ? 1 : 0.5), maxRank: r, boss },
        first,
        boss,
    };
}

// ── WHAT DRIVING SOMEBODY OFF PAYS ───────────────────────────────────────────────────────────────────────────
// Repelling a raid used to pay a flat 12 doubloons, and the screen that announced it rendered the row's `gold`
// column — which the insert hardcodes to 0. So the one reward in the game you never chose to take was reported
// to the member as "You repelled 1 raid! +0" with "+0g" beside the raider's name. It was not nothing; it was
// twelve doubloons described as nothing, which is worse than nothing.
//
// It pays out of the SAME TABLE as sinking a ship now, at a defender's share, because the thing that happened
// is the same thing: you beat a hull of that rank. One reward design for ship battles was the point of
// finishToRaidBattle's rewrite, and a second bespoke payout for the defence half would undo it.
//
// ⚠️ GENEROUS ON PURPOSE, AND THE FREQUENCY IS WHY. Measured before choosing the number: the whole Den
// produces one to three repels a DAY, and nobody has been raided more than once in any three-day window.
// 220 repels all time. A reward nobody can farm, cannot choose to take, and sees about once a week is the
// wrong place to be careful — see [[economy-nerf-measure-daily-total]], which is about the daily total, and
// the daily total here is two.
//
// Still a SHARE rather than the whole hand: raiding costs a daily raid and defending costs nothing, so
// attacking has to remain the better way to earn or the ladder stops meaning anything.
export const DEFENCE_SHARE = 0.6;

export function defenceReward(rank) {
    const r = fleetReward(rank, { first: true, boss: false });
    if (!r) return null;
    const cut = (n) => (n ? Math.max(1, Math.round(n * DEFENCE_SHARE)) : n);
    return {
        ...r,
        doubloons: cut(r.doubloons),
        gold: cut(r.gold),
        xp: cut(r.xp),
        fragments: cut(r.fragments),
        parts: r.parts ? { ...r.parts, n: cut(r.parts.n) } : null,
        // No seed. It is the first-sinking flavour on the fleet ladder and a repel is not a rung you climbed.
        seed: false,
        loot: r.loot ? { ...r.loot, chance: r.loot.chance * DEFENCE_SHARE } : null,
        first: false,
    };
}

// The fleet as the client renders it: everything up to and including the next unfought rank, so the ladder is
// visible ahead of you (an unbeaten rung names what you are climbing toward) and nothing past the horizon.
export function fleetView(depth = 0) {
    const next = Math.min(MAX_FLEET_RANK, depth + 1);
    // Two ranks PAST the one you can fight, shown locked. The list is merged with member rivals now and sorted
    // by difficulty — without the locked rungs the ladder just stopped, and a rival ranked above your depth
    // appeared to be the next thing in a fleet that had apparently run out. Seeing what is behind the door is
    // also the reason to keep climbing.
    const show = Math.min(MAX_FLEET_RANK, next + 2);
    return FLEET.filter((f) => f.rank <= show).map((f) => ({
        rank: f.rank, name: f.name, cls: f.cls, art: fleetArt(f), boss: Boolean(f.boss), flavor: f.flavor,
        // The captain, so the picker can show the person on their deck rather than an empty hull.
        crew: fleetCaptain(f),
        guns: f.guns, hp: f.hp, ammo: f.ammo, hullGrade: hullGrade(f.hp),
        beaten: f.rank <= depth,
        current: f.rank === next && f.rank > depth,
        locked: f.rank > next,
        reward: fleetReward(f.rank, { first: f.rank > depth }),
    }));
}
