import "server-only";

import { db } from "@/lib/db";
import { generateImage, generateWideSceneImage, generateSceneImage } from "@/lib/marketplace/openai-image.js";

// AI art for the side-scrolling Wolf Den Town: one WIDE panoramic street background (repeated/mirrored so it
// scrolls forever) + transparent BUILDING sprites laid on top of it. Static/shared — generate once + store.

const STREET_STYLE =
    "painterly 2D side-scrolling video-game background, warm golden-hour dusk, cohesive fantasy action-RPG town, soft lantern glow, rich but not busy, no text, no watermark.";
const CRITTER_STYLE =
    "a single cute mascot CHARACTER sprite, full body, three-quarter view facing forward, painterly fantasy cel-shaded style with soft dark ink linework (NOT a white outline), warm vibrant colors, a strong readable silhouette, centered. Floats ALONE on a FULLY TRANSPARENT background (alpha) — absolutely NO white sticker outline, NO die-cut border, NO rim, NO halo, NO glow ring, NO drop shadow, NO ground, NO scenery, NO tile. Nothing but the critter. No text, no watermark, no border.";
const BUILDING_STYLE =
    "a single isolated 2D game-art building, the WHOLE building centered and fully visible, painterly fantasy action-RPG style with clean confident outlines and cel-shaded vibrant colors, strong readable silhouette. ISOLATED as a clean cutout on a FULLY TRANSPARENT background (alpha channel) — absolutely NO background scenery, NO sky, NO ground, NO cobblestones, NO haze, fog, or ambient glow behind the building. Nothing but the building itself. No people, no text, no logo, no watermark, no border.";

const ART_PROMPTS = {
    // ── Layered/parallax approach (reliable): a GENERIC tiling far sky + a seamless cobble ground texture; all
    // the uniqueness lives in the separate building sprites laid on top. Only these two are ever "tiled", and
    // they're the two things that tile flawlessly (a generic sky mirrors invisibly; a texture repeats cleanly).
    sky:
        `A bright cheerful DAYTIME BLUE SKY backdrop for a fantasy town — soft fluffy white cumulus clouds of NATURALLY VARIED sizes and organic irregular shapes, scattered ORGANICALLY across the sky (some loosely clustered, some lone wisps, plenty of open clear blue between them), a natural-looking sky — absolutely NOT a uniform grid, NOT evenly-spaced, NOT a repeating pattern. Along the VERY BOTTOM edge only, a LOW, SMALL, FAINT, pale-blue silhouette of far-off medieval rooftops, small and washed-out (far away). CRITICAL: absolutely NO orange, NO tan, NO dust-storm haze, NO cream/beige haze band, NO fog streak — just a friendly natural BLUE sky with soft white clouds. Designed to tile horizontally with no hard seam at the left/right edges. Painterly 2D video-game background, clean and inviting, no text, no watermark, no border.`,
    cobble:
        `A seamless COBBLESTONE STREET ground texture seen at a slight downward angle — worn rounded grey-brown cobbles with mortar gaps, warm even dusk lighting, uniform across the WHOLE image with no focal point, NO objects, NO people, NO buildings, NO sky, NO horizon — just repeating cobblestones, designed to tile left-to-right. ${STREET_STYLE}`,
    // Farm RAISED BED planter — real art to replace the flat CSS plot. Drawn nearly FRONT-ON (flat 2D farm-game
    // view, NOT steep isometric) so it sits naturally in the side-on garden scene. Plants grow out of its soil.
    farm_bed:
        `A single empty RAISED GARDEN BED planter drawn nearly FRONT-ON at a SHALLOW downward tilt — a flat 2D side-scroller farm-game view, NOT a steep isometric angle: you mainly see the low wooden-plank front rail with rounded corner posts, and just above it the dark rich tilled soil surface (gentle furrow rows, a few pebbles) tilted enough to plant in. A wide, low, shallow bed. NO plants, NO crops — empty soil ready to plant. Painterly fantasy farm game-art, warm daylight, clean confident outlines and cel-shaded vibrant colors, a strong readable silhouette. ISOLATED as a clean cutout on a FULLY TRANSPARENT background (alpha channel) — absolutely NO grass, NO surrounding ground, NO scenery, NO drop shadow, NO glow behind it. Nothing but the raised bed. No text, no watermark, no border.`,
    // Pet passive-bonus STAT ICONS — small emblem sprites in the game's painterly cel-shaded style (style proof:
    // xp, gold, fortune; the rest follow once approved). CRITICAL: no white sticker rim / die-cut border / halo.
    stat_xp:
        `A single small game ICON of a glowing golden STAR-BURST / sparkle for experience & leveling up. Painterly fantasy cel-shaded style with soft dark-brown ink linework (NOT a white outline), bright radiant golds with a warm inner glow, strong readable silhouette, centered. The subject floats ALONE on a FULLY TRANSPARENT background (alpha) — absolutely NO white sticker outline, NO die-cut border, NO rim, NO halo, NO glow ring around it, NO drop shadow, NO tile, NO card, NO scenery. Nothing but the emblem itself. No text, no watermark, no border.`,
    stat_gold:
        `A single small game ICON of a plump drawstring COIN POUCH overflowing with shiny gold coins, for gold/wealth. Painterly fantasy cel-shaded style with soft dark-brown ink linework (NOT a white outline), warm golds and browns, strong readable silhouette, centered. The subject floats ALONE on a FULLY TRANSPARENT background (alpha) — absolutely NO white sticker outline, NO die-cut border, NO rim, NO halo, NO glow ring around it, NO drop shadow, NO tile, NO card, NO scenery. Nothing but the pouch itself. No text, no watermark, no border.`,
    stat_fortune:
        `A single small game ICON of a lucky FOUR-LEAF CLOVER with a subtle golden sparkle, for fortune/luck. Painterly fantasy cel-shaded style with soft dark-green ink linework (NOT a white outline), vivid greens, strong readable silhouette, centered. The subject floats ALONE on a FULLY TRANSPARENT background (alpha) — absolutely NO white sticker outline, NO die-cut border, NO rim, NO halo, NO glow ring around it, NO drop shadow, NO tile, NO card, NO scenery. Nothing but the clover itself. No text, no watermark, no border.`,
    stat_might:
        `A single small game ICON of a mighty upright STEEL SWORD, for raw might/damage. Painterly fantasy cel-shaded style with soft dark ink linework (NOT a white outline), steel greys with a warm gold hilt, strong readable silhouette, centered. Floats ALONE on a FULLY TRANSPARENT background (alpha) — absolutely NO white sticker outline, NO die-cut border, NO rim, NO halo, NO glow ring, NO drop shadow, NO tile, NO card, NO scenery. Nothing but the sword. No text, no watermark, no border.`,
    stat_critchance:
        `A single small game ICON of a round red-and-white TARGET / bullseye with an arrow struck in the center, for critical-hit chance. Painterly fantasy cel-shaded style with soft dark ink linework (NOT a white outline), reds and creams, strong readable silhouette, centered. Floats ALONE on a FULLY TRANSPARENT background (alpha) — absolutely NO white sticker outline, NO die-cut border, NO rim, NO halo, NO glow ring, NO drop shadow, NO tile, NO card, NO scenery. Nothing but the target. No text, no watermark, no border.`,
    stat_critpower:
        `A single small game ICON of a bursting orange IMPACT STAR / comic-style explosion burst, for critical-hit power. Painterly fantasy cel-shaded style with soft dark ink linework (NOT a white outline), fiery oranges and yellows, strong readable silhouette, centered. Floats ALONE on a FULLY TRANSPARENT background (alpha) — absolutely NO white sticker outline, NO die-cut border, NO rim, NO halo, NO glow ring, NO drop shadow, NO tile, NO card, NO scenery. Nothing but the burst. No text, no watermark, no border.`,
    stat_ferocity:
        `A single small game ICON of a fierce curling FLAME, for ferocity/damage. Painterly fantasy cel-shaded style with soft dark ink linework (NOT a white outline), hot reds-oranges-yellows, strong readable silhouette, centered. Floats ALONE on a FULLY TRANSPARENT background (alpha) — absolutely NO white sticker outline, NO die-cut border, NO rim, NO halo, NO glow ring, NO drop shadow, NO tile, NO card, NO scenery. Nothing but the flame. No text, no watermark, no border.`,
    stat_seedluck:
        `A single small game ICON of a plump brown SEED / acorn with a tiny green sprout and a small golden sparkle, for seed luck. Painterly fantasy cel-shaded style with soft dark ink linework (NOT a white outline), warm browns and fresh greens, strong readable silhouette, centered. Floats ALONE on a FULLY TRANSPARENT background (alpha) — absolutely NO white sticker outline, NO die-cut border, NO rim, NO halo, NO glow ring, NO drop shadow, NO tile, NO card, NO scenery. Nothing but the seed. No text, no watermark, no border.`,
    stat_growspeed:
        `A single small game ICON of a fresh green SPROUT shooting upward with a couple of little motion/speed streaks, for faster crop growth. Painterly fantasy cel-shaded style with soft dark-green ink linework (NOT a white outline), vivid greens, strong readable silhouette, centered. Floats ALONE on a FULLY TRANSPARENT background (alpha) — absolutely NO white sticker outline, NO die-cut border, NO rim, NO halo, NO glow ring, NO drop shadow, NO tile, NO card, NO scenery. Nothing but the sprout. No text, no watermark, no border.`,
    stat_petbond:
        `A single small game ICON of a soft blue glowing PAW PRINT, for the pet bond. Painterly fantasy cel-shaded style with soft dark ink linework (NOT a white outline), gentle blues, strong readable silhouette, centered. Floats ALONE on a FULLY TRANSPARENT background (alpha) — absolutely NO white sticker outline, NO die-cut border, NO rim, NO halo, NO glow ring, NO drop shadow, NO tile, NO card, NO scenery. Nothing but the paw print. No text, no watermark, no border.`,
    stat_tickets:
        `A single small game ICON of a golden RAFFLE TICKET (a torn admission ticket with a perforated stub), for boss-raffle entries. Painterly fantasy cel-shaded style with soft dark ink linework (NOT a white outline), warm golds and reds, strong readable silhouette, centered. Floats ALONE on a FULLY TRANSPARENT background (alpha) — absolutely NO white sticker outline, NO die-cut border, NO rim, NO halo, NO glow ring, NO drop shadow, NO tile, NO card, NO scenery. Nothing but the ticket. No text, no watermark, no border.`,
    // Custom dice sprite — a pair of tavern dice spilling from a leather cup (replaces the 🎲 emoji at the
    // merchant gamble + the tavern dice table).
    dice:
        `A pair of ivory tavern DICE with crisp black pips, one mid-tumble, spilling out of a worn brown leather dice CUP tipped on its side. Painterly fantasy game-art, warm and inviting, clean confident outlines and cel-shaded vibrant colors, a strong readable silhouette, a hint of motion. ISOLATED as a clean cutout on a FULLY TRANSPARENT background (alpha channel) — absolutely NO table, NO surface, NO scenery, NO drop shadow, NO glow behind it. Nothing but the cup and dice. No text, no logo, no watermark, no border.`,
    // Opaque WIDE interior room for the walkable tavern — an EMPTY room (characters are placed on top as NPCs).
    tavern_interior:
        `A WIDE panoramic cozy fantasy medieval TAVERN INTERIOR, a long room seen straight-on side-scroller style: on the LEFT a long wooden BAR counter with kegs, taps, bottles and hanging mugs (but NOBODY behind it); in the CENTER a big crackling stone FIREPLACE casting warm orange glow, with a few empty round wooden tables and stools; on the RIGHT a cozy corner with a small gambling table and stools; heavy timber ceiling beams, hanging iron lanterns, barrels, a warm plank floor running the whole width. IMPORTANT: NO people, NO characters, NO patrons anywhere — an EMPTY inviting room so game characters can stand in it. Rich warm cozy firelit mood. Painterly 2D video-game background, no text, no watermark, no UI, no border.`,
    // Tavern NPC CHARACTERS (people, placed in the walkable room).
    barkeep: `A single 2D video-game CHARACTER sprite of a friendly TAVERN BARKEEP: a stout jolly bearded HUMAN man in a leather apron over a rolled-sleeve shirt, a bar towel over one shoulder, holding up a frothing mug of ale with a welcoming grin, full body head-to-boots, three-quarter view facing forward. This is a PERSON / character — NOT a building, NOT a bar. Painterly fantasy action-RPG style with clean confident outlines and cel-shaded vibrant colors, strong readable silhouette. Isolated as a clean cutout on a FULLY TRANSPARENT background (alpha channel) — absolutely NO background, NO bar, NO scenery, NO ground, NO glow. Nothing but the character. No text, no logo, no watermark, no border.`,
    gambler: `A single 2D video-game CHARACTER sprite of a sly TAVERN GAMBLER SEATED on a stool: a lean roguish HUMAN man in a hooded cloak and vest with a smirk, leaning forward with a pair of DICE in one raised hand as if mid-toss, SITTING on a wooden stool (show him seated, knees bent), three-quarter view facing forward. This is a PERSON / character — NOT a building, NOT a table. Painterly fantasy action-RPG style with clean confident outlines and cel-shaded vibrant colors, strong readable silhouette. Isolated as a clean cutout on a FULLY TRANSPARENT background (alpha channel) — absolutely NO background, NO table, NO scenery, NO ground, NO glow. Nothing but the character. No text, no logo, no watermark, no border.`,
    mid:
        `A MIDGROUND row of nearer medieval fantasy town buildings and rooftops along the BOTTOM of the frame — timber-and-stone houses with warm brown timber and terracotta tiled roofs, chimneys, a couple of taller buildings, lit by soft NATURAL DAYTIME light. CRITICAL: NO dusk, NO orange/warm backlight, NO glowing sky, and absolutely NO haze, fog, cream/tan band or atmospheric glow behind or around the buildings. The TOP two-thirds of the image is FULLY TRANSPARENT (alpha) with NOTHING in it — no baked sky, no clouds, no haze — just clean building rooftops cut out against transparency along the bottom. Designed to tile left-to-right, no ground, no street, no people, no text. Painterly 2D game art, clean cel-shaded, no text, no watermark, no border.`,
    // "Grow the Plaza" DEPTH layers — each funded level stacks one more parallax band FURTHER back (behind the
    // midground), so the town visibly grows deeper as it's invested in. Transparent-topped, tiling silhouettes.
    depth1:
        `A distant skyline of medieval TOWN SPIRES, steeples and steep rooftops strung along the horizon, SMALL and hazy in soft DAYTIME light (cool pale blue-grey atmospheric haze, NOT dusk/orange) — a farther-off quarter of the same town, kept modest and low so it reads as sitting BEHIND the nearer rooftops under a blue sky. CRITICAL: absolutely NO bright white/cream glow band at the base, NO fog streak, NO haze band — a clean pale silhouette against transparency. The TOP ~74% of the image is FULLY TRANSPARENT (alpha) with nothing in it; only the low distant silhouette occupies the bottom. Designed to tile left-to-right, no ground, no street, no people, no text.`,
    depth2:
        `A distant range of low rolling HILLS and soft blue-grey MOUNTAINS along the horizon, with a few tiny far watchtowers nestled among them, in soft DAYTIME light (cool pale blue-grey atmospheric haze, NOT dusk/orange), very soft and desaturated as if seen far away, sitting BEHIND a farther town skyline under a blue sky. CRITICAL: absolutely NO orange, NO tan, NO warm/cream glow band, NO dusk — a clean cool pale silhouette against transparency. The TOP ~72% of the image is FULLY TRANSPARENT (alpha) with nothing in it; only the low hill silhouette occupies the bottom. Designed to tile left-to-right, no ground, no street, no people, no text. Painterly 2D game background, no text, no watermark, no border.`,
    depth3:
        `A far skyline of grand CASTLE KEEPS and citadel towers with fluttering banners crowning distant hills, majestic and aspirational, in soft DAYTIME light (cool pale blue-grey atmospheric haze, NOT dusk/orange) softening them into the horizon under a blue sky. CRITICAL: absolutely NO orange, NO tan, NO warm/cream glow band, NO dusk — a clean cool pale silhouette against transparency. The TOP ~62% of the image is FULLY TRANSPARENT (alpha) with nothing in it; only the far castle silhouette occupies the lower portion. Designed to tile left-to-right, no ground, no street, no people, no text. Painterly 2D game background, no text, no watermark, no border.`,
    // The plaza CENTERPIECE — a grand arted town-square fountain (a real landmark, replacing the old emoji statue).
    centerpiece:
        `A grand ornate medieval town-square FOUNTAIN as a centerpiece: a round tiered basin of carved pale weathered stone with clear water arcing and spilling between the tiers, and standing proudly atop the center a carved statue of a HOWLING WOLF, warm golden dusk lantern glow catching the splashing water, a scatter of coins glinting in the basin. A single isolated 2D game-art object, the WHOLE fountain centered and fully visible, painterly fantasy action-RPG style with clean confident outlines and cel-shaded vibrant colors, a strong readable silhouette. ISOLATED as a clean cutout on a FULLY TRANSPARENT background (alpha channel) — absolutely NO background scenery, NO sky, NO ground, NO cobblestones, NO haze, fog, or glow behind it. Nothing but the fountain. No people, no text, no logo, no watermark, no border.`,
    fg:
        `A LOW foreground border running straight across the BOTTOM of the frame — a weathered medieval stone retaining wall / cobbled curb roughly waist-high, topped here and there with a short wooden rail, tufts of grass and moss, a couple of wooden barrels and a crate, and a short lamp-post with a warm glowing lantern. Nearer and larger-detailed than the background — this is the near edge of the town square where the street meets the buildings behind it. The TOP ~65% of the image is FULLY TRANSPARENT (alpha) with nothing in it — ONLY the low wall and its props occupy the bottom. Designed to tile left-to-right, no full buildings, no sky, no people, no text. ${STREET_STYLE}`,
    // Legacy single wide background (kept only as a fallback if the layers aren't generated).
    background:
        `A wide empty fantasy COBBLESTONE town street at warm golden dusk, worn cobblestones underfoot, a low stone curb, distant medieval town rooftops, chimneys and a couple of towers on the horizon, warm sky fading to dusky purple, a few hanging lanterns and string lights, cozy and inviting, NO people, NO large foreground buildings (leave the street open) — a clean side-scroller street the player walks along. ${STREET_STYLE}`,
    tavern: `A cozy fantasy TAVERN — a timber-framed inn with warm-lit windows, a hanging wooden sign shaped like a foaming beer mug, a small awning over the door. ${BUILDING_STYLE}`,
    boss: `An imposing stone BATTLE ARENA gatehouse — a coliseum-style entrance with crossed-swords banners, two iron braziers with flame, heavy arched wooden doors. ${BUILDING_STYLE}`,
    forge: `A blacksmith's FORGE — a stone-and-timber smithy with a glowing orange furnace opening, an anvil beside the door, a chimney with a small wisp of smoke, a hanging hammer-and-anvil sign. ${BUILDING_STYLE}`,
    shop: `A GENERAL STORE trading post — a wooden shopfront with a striped awning, a couple of barrels and crates of goods by the door, a hanging sign with a coin pouch. ${BUILDING_STYLE}`,
    docks: `A wooden HARBOR DOCKHOUSE with a small moored sailing ship beside it, coiled ropes, barrels and crates, a lantern on a post. ${BUILDING_STYLE}`,
    farm: `A rustic FARM barn — a red-brown barn with a hayloft, a wooden fence gate, a couple of pumpkins and a wheat sheaf by the door, a little scarecrow. ${BUILDING_STYLE}`,
    // Trading Post project icon — a market-stall sprite (replaces the 🧳 emoji on the Town Development card).
    trading_post: `A bustling TRADING POST market stall — a wooden merchant stall with a striped canvas awning, a counter stacked with crates, barrels, rolled rugs, sacks of goods, treasure chests and hanging lanterns, a small hanging sign shaped like a coin. ${BUILDING_STYLE}`,
    // Town Development project icons (sprites replacing the emoji on each upgrade card). Each is a small isolated
    // building/emblem sprite. `vault` + `festival` double as the plaza BUILDING art once those unlocks are funded.
    prosperity: `A grand civic TOWN HALL of prosperity — a stately classical hall with tall columns, a golden domed roof, a hanging crest banner, a coin-and-laurel emblem over the doors, warm and inviting. ${BUILDING_STYLE}`,
    townscape: `A cluster of medieval fantasy TOWN BUILDINGS forming a small growing skyline — several timber-and-stone houses and one taller tower packed close together at varying heights, reading as a thriving town quarter. ${BUILDING_STYLE}`,
    garrison: `A fortified stone GARRISON gatehouse — battlemented walls with a watchtower, a crossed-swords banner, an iron portcullis, a couple of spears and a shield racked by the heavy door. ${BUILDING_STYLE}`,
    vault: `A sturdy stone treasury VAULT building — a strong bank with a heavy round iron vault door, stacks of gold coins and a small treasure chest by the entrance, a coin crest on the pediment, iron-barred windows. ${BUILDING_STYLE}`,
    festival: `A colorful FESTIVAL STAGE — a raised wooden performance stage with hanging paper lanterns and rows of triangular pennant-flag bunting in bright colors, and a plain decorative curved wooden top beam (NO sign, NO banner with writing). CRITICAL: absolutely NO letters, NO words, NO text, NO writing anywhere on it. Festive and grand. ${BUILDING_STYLE}`,
    // Farm-encounter CRITTERS — cute, FRIENDLY gift-bringing garden critters (the encounter is pure upside, so
    // they read as adorable and welcoming, NOT menacing). Small mascot sprites, transparent, no white rim.
    enc_rat: `A single adorable friendly cartoon FIELD MOUSE mascot, sitting up on its hind legs holding a tiny golden seed in its little paws with a cheerful smile, big sparkly eyes, round and cute. ${CRITTER_STYLE}`,
    enc_crow: `A single plump friendly cartoon CROW mascot (glossy blue-black feathers), standing cheerfully with a small green sprout held in its beak, big friendly eyes, round and cute (NOT scary). ${CRITTER_STYLE}`,
    enc_raccoon: `A single adorable friendly cartoon RACCOON mascot with its classic mask and ringed tail, sitting up holding a little treasure chest or shiny coin with a mischievous happy grin, big sparkly eyes, round and cute. ${CRITTER_STYLE}`,
    enc_boar: `A single jolly friendly cartoon little TRUFFLE PIGLET / baby boar mascot, chubby and pink-brown with tiny tusks, holding a leafy truffle with a happy grin, big cute eyes, round and adorable (NOT menacing). ${CRITTER_STYLE}`,
    enc_scarecrow: `A single cheerful friendly cartoon SCARECROW mascot — a smiling straw scarecrow in a patched hat and shirt, arms open in a welcoming wave, hugging a small orange pumpkin, warm and jolly (NOT creepy). ${CRITTER_STYLE}`,
    // Town NPC — a CHARACTER sprite (person, not a building) who stands by the Forge. Uses a character-style
    // prompt (the building style biased the model into drawing a smithy).
    smith: `A single 2D video-game CHARACTER sprite of a friendly burly BLACKSMITH: a bearded HUMAN MAN, full body head-to-boots, standing, wearing a leather apron and rolled sleeves, resting a large smithing hammer on one shoulder, three-quarter view facing slightly forward, warm and welcoming. This is a PERSON / character — NOT a building, NOT a house. Painterly fantasy action-RPG style with clean confident outlines and cel-shaded vibrant colors, strong readable silhouette. Isolated as a clean cutout on a FULLY TRANSPARENT background (alpha channel) — absolutely NO background, NO scenery, NO building, NO forge, NO ground, NO sky, NO glow. Nothing but the character. No text, no logo, no watermark, no border.`,
    // Town-event enemies — menacing but stylized creatures to attack during a raid.
    bandit: `A single 2D video-game CHARACTER sprite of a menacing fantasy BANDIT RAIDER: a rugged HUMAN outlaw in dark leather armor and a hood or bandana mask over the lower face, brandishing a curved sword or dagger, mid-crouch aggressive battle stance, full body head-to-boots, three-quarter view facing forward toward the viewer, villainous but cartoon-stylized (not gory). This is a PERSON / character — NOT a building. Painterly fantasy action-RPG style with clean confident outlines and cel-shaded vibrant colors, strong readable silhouette. Isolated as a clean cutout on a FULLY TRANSPARENT background (alpha channel) — absolutely NO background, NO scenery, NO ground, NO sky, NO glow. Nothing but the character. No text, no logo, no watermark, no border.`,
    goblin: `A single 2D video-game CHARACTER sprite of a menacing but cartoon-stylized GOBLIN RAIDER: a small wiry green-skinned goblin with big pointed ears, a wicked toothy grin and beady eyes, wearing scrappy leather scraps, brandishing a crude jagged dagger, aggressive crouched battle stance, full body head-to-toe, three-quarter view facing forward. This is a CREATURE / character — NOT a building. Painterly fantasy action-RPG style with clean confident outlines and cel-shaded vibrant colors, strong readable silhouette. Isolated as a clean cutout on a FULLY TRANSPARENT background (alpha channel) — absolutely NO background, NO scenery, NO ground, NO sky, NO glow. Nothing but the character. No text, no logo, no watermark, no border.`,
    golem: `A single 2D video-game CHARACTER sprite of a hulking TREASURE GOLEM: a massive lumbering creature built of rough stone and cracked earth, its body studded and overflowing with glinting GOLD COINS and colorful gemstones spilling from the seams, glowing amber eyes, heavy imposing standing pose with big fists, full body head-to-feet, three-quarter view facing forward, awe-inspiring (not gory). This is a CREATURE / character — NOT a building. Painterly fantasy action-RPG style with clean confident outlines and cel-shaded vibrant colors, strong readable silhouette. Isolated as a clean cutout on a FULLY TRANSPARENT background (alpha channel) — absolutely NO background, NO scenery, NO ground, NO sky, NO glow. Nothing but the character. No text, no logo, no watermark, no border.`,
    // Town NPCs (characters, NOT buildings) who stand in the plaza.
    crier: `A single 2D video-game CHARACTER sprite of a cheerful TOWN CRIER: a HUMAN MAN in a colorful medieval tabard and feathered cap, one hand raised ringing a big brass hand-bell, the other holding a rolled parchment scroll, mouth open mid-announcement, full body head-to-boots, three-quarter view facing forward, lively and welcoming. This is a PERSON / character — NOT a building. Painterly fantasy action-RPG style with clean confident outlines and cel-shaded vibrant colors, strong readable silhouette. Isolated as a clean cutout on a FULLY TRANSPARENT background (alpha channel) — absolutely NO background, NO scenery, NO ground, NO sky, NO glow. Nothing but the character. No text, no logo, no watermark, no border.`,
    merchant: `A single 2D video-game CHARACTER sprite of a friendly TRAVELING MERCHANT: a HUMAN peddler in a hooded traveling cloak and many-pocketed vest, an overstuffed backpack of wares and trinkets, holding up a small treasure chest or coin pouch with a sly welcoming grin, full body head-to-boots, three-quarter view facing forward. This is a PERSON / character — NOT a building, NOT a market stall. Painterly fantasy action-RPG style with clean confident outlines and cel-shaded vibrant colors, strong readable silhouette. Isolated as a clean cutout on a FULLY TRANSPARENT background (alpha channel) — absolutely NO background, NO scenery, NO ground, NO sky, NO glow, NO stall. Nothing but the character. No text, no logo, no watermark, no border.`,
    questgiver: `A single 2D video-game CHARACTER sprite of a friendly QUEST-GIVER quartermaster: a grizzled seasoned HUMAN adventurer in a leather jerkin and short cloak, holding up a rolled bounty scroll in one hand and gesturing invitingly with the other, a satchel at the hip, full body head-to-boots, three-quarter view facing forward, warm and welcoming. This is a PERSON / character — NOT a building, NOT a notice board. Painterly fantasy action-RPG style with clean confident outlines and cel-shaded vibrant colors, strong readable silhouette. Isolated as a clean cutout on a FULLY TRANSPARENT background (alpha channel) — absolutely NO background, NO scenery, NO ground, NO sky, NO glow. Nothing but the character. No text, no logo, no watermark, no border.`,
};

// ── Crop GROWTH sprites: each crop gets 3 stages (sprout → growing → ripe) so plots look like the plant is
// actually growing OUT of the bed, not a pickable emoji. Stage 1 (sprout) is shared. Plants are rooted at the
// bottom and grow upward; NO soil/pot/bed (they sit on the arted bed), NO white sticker rim.
const _cropPlant = (stage, subject) =>
    `A single ${stage}, a 2D farm-game PLANT sprite viewed FRONT-ON, rooted at the very BOTTOM edge and growing UPWARD (${subject}). Painterly cel-shaded style with soft dark ink linework (NOT a white outline), vivid natural colors, strong readable silhouette. The plant floats ALONE on a FULLY TRANSPARENT background (alpha) — absolutely NO soil, NO dirt, NO pot, NO planter, NO bed, NO ground, NO white sticker outline, NO die-cut border, NO halo, NO drop shadow, NO scenery. Nothing but the plant itself. No text, no watermark, no border.`;
const CROP_RIPE = {
    wheat: "tall golden WHEAT stalks topped with heavy ripe grain heads",
    carrot: "bushy green CARROT tops with the bright orange carrot crown just showing at the base",
    potato: "a leafy green POTATO plant dotted with small white flowers",
    strawberry: "a low STRAWBERRY plant with green leaves and a few ripe red strawberries",
    corn: "a tall CORN stalk with broad green leaves and one ripe golden-yellow corn cob",
    grape: "a GRAPEVINE with green leaves and a full cluster of ripe purple grapes",
    pumpkin: "a sprawling PUMPKIN vine with big leaves and a plump ripe orange pumpkin",
    goldenapple: "a small leafy branch bearing a glowing GOLDEN APPLE among green leaves",
    starfruit: "an exotic plant bearing a glowing yellow STAR-SHAPED starfruit with faint sparkles",
};
const _cropPrompts = { crop_sprout: _cropPlant("small green SEEDLING SPROUT — two tiny leaves on a short pale stem, freshly emerged", "just the little sprout") };
for (const [id, ripe] of Object.entries(CROP_RIPE)) {
    _cropPrompts[`crop_${id}_grow`] = _cropPlant(`young ${id} plant partway grown — a leafy green stem with several leaves and NO ripe fruit yet`, "a healthy leafy young plant, taller than a sprout");
    _cropPrompts[`crop_${id}_ripe`] = _cropPlant(`mature ${id} plant heavy with its crop`, ripe);
}
Object.assign(ART_PROMPTS, _cropPrompts);

export const TOWN_ART_KEYS = Object.keys(ART_PROMPTS);

// Generate (or regenerate) one town art asset and store its URL.
export async function generateTownArt(key) {
    const prompt = ART_PROMPTS[key];
    if (!prompt) throw new Error("Unknown town art key");
    let url;
    if (key === "background") url = await generateWideSceneImage(prompt, { pathPrefix: "marketplace/town", panels: 3 });
    else if (key === "tavern_interior") url = await generateWideSceneImage(prompt, { pathPrefix: "marketplace/town", panels: 2 }); // WIDE scrollable tavern room
    else if (key === "sky" || key === "cobble") url = await generateSceneImage(prompt, { pathPrefix: "marketplace/town" }); // opaque scene layers
    else url = await generateImage(prompt, { size: "1024x1024", pathPrefix: "marketplace/town", deHalo: true }); // transparent building sprite
    await db.query(
        `INSERT INTO mkt_town_art (art_key, url, updated_at) VALUES ($1, $2, NOW())
         ON CONFLICT (art_key) DO UPDATE SET url = $2, updated_at = NOW()`,
        [key, url]
    );
    return url;
}

// Status for the admin tool: which keys have art yet.
export async function townArtStatus() {
    const rows = await db.query(`SELECT art_key, url FROM mkt_town_art`).catch(() => []);
    const have = Object.fromEntries(rows.map((r) => [r.art_key, r.url]));
    return { keys: TOWN_ART_KEYS.map((k) => ({ key: k, url: have[k] || null })), done: TOWN_ART_KEYS.filter((k) => have[k]).length, total: TOWN_ART_KEYS.length };
}
