import "server-only";

import { randomUUID } from "node:crypto";

import { db } from "@/lib/db";
import { createServerLogger } from "@/lib/server-logger";

const payoutsLogger = createServerLogger({ source: "api", subsystem: "consignment-payouts" });

function toIso(value) {
    return value ? new Date(value).toISOString() : null;
}

function formatCurrency(value) {
    return new Intl.NumberFormat("en-US", {
        style: "currency",
        currency: "USD",
    }).format(Number(value || 0));
}

function escapeHtml(value) {
    return String(value || "")
        .replaceAll("&", "&amp;")
        .replaceAll("<", "&lt;")
        .replaceAll(">", "&gt;")
        .replaceAll('"', "&quot;")
        .replaceAll("'", "&#39;");
}

function createReceiptNumber() {
    const datePart = new Date().toISOString().slice(0, 10).replaceAll("-", "");
    const shortId = randomUUID().replaceAll("-", "").slice(0, 10).toUpperCase();

    return `WD-${datePart}-${shortId}`;
}

function buildReceiptHtml(payload) {
    return `
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Wolf Den Consignment Receipt ${escapeHtml(payload.receiptNumber)}</title>
</head>
<body style="font-family: Georgia, 'Times New Roman', serif; background: #f6f1e7; color: #1f1a14; margin: 0; padding: 24px;">
  <div style="max-width: 760px; margin: 0 auto; background: #fffdf8; border: 1px solid #d5c7aa; border-radius: 10px; overflow: hidden;">
    <div style="padding: 18px 22px; background: linear-gradient(135deg, #2b1f12, #4b331c); color: #f7e7c1;">
      <h1 style="margin: 0; font-size: 1.4rem;">The Wolf Den</h1>
      <p style="margin: 6px 0 0; opacity: 0.95;">Consignment Payout Receipt</p>
    </div>
    <div style="padding: 22px;">
      <p style="margin: 0 0 8px;"><strong>Receipt #:</strong> ${escapeHtml(payload.receiptNumber)}</p>
      <p style="margin: 0 0 8px;"><strong>Paid To:</strong> ${escapeHtml(payload.displayName)}</p>
      <p style="margin: 0 0 8px;"><strong>Email:</strong> ${escapeHtml(payload.email)}</p>
      <p style="margin: 0 0 8px;"><strong>Paid At:</strong> ${escapeHtml(new Date(payload.paidAt).toLocaleString("en-US"))}</p>
      <p style="margin: 0 0 8px;"><strong>Payment Method:</strong> ${escapeHtml(payload.paymentMethod || "manual")}</p>
      <hr style="margin: 18px 0; border: 0; border-top: 1px solid #dccfb4;" />
      <p style="font-size: 1.22rem; margin: 0 0 10px;"><strong>Payout Amount:</strong> ${formatCurrency(payload.amount)}</p>
      <p style="margin: 0 0 8px;"><strong>Total Estimated Owed Before This Payout:</strong> ${formatCurrency(payload.owedBefore)}</p>
      <p style="margin: 0 0 8px;"><strong>Total Paid To Date:</strong> ${formatCurrency(payload.totalPaidAfter)}</p>
      <p style="margin: 0 0 8px;"><strong>Current Owed After Payout:</strong> ${formatCurrency(payload.owedAfter)}</p>
      ${payload.note ? `<p style="margin-top: 14px;"><strong>Note:</strong> ${escapeHtml(payload.note)}</p>` : ""}
      <hr style="margin: 18px 0; border: 0; border-top: 1px solid #dccfb4;" />
      <p style="margin: 0; color: #5f5344; font-size: 0.92rem;">This receipt was generated by the Wolf Den consignment portal at payout time and stored for future reference.</p>
    </div>
  </div>
</body>
</html>`.trim();
}

function mapPayoutRow(row) {
    return {
        id: row.id,
        amount: Number(row.amount || 0),
        paidAt: toIso(row.paid_at),
        paymentMethod: row.payment_method || null,
        note: row.note || null,
        receiptNumber: row.receipt_number,
        createdAt: toIso(row.created_at),
    };
}

export async function listPayoutsForConsignor(consignorId) {
    payoutsLogger.info("consignment.payouts.list.started", { consignorId });

    const rows = await db.query(
        `SELECT id, amount, paid_at, payment_method, note, receipt_number, created_at
         FROM consignor_payouts
         WHERE consignor_id = $1
         ORDER BY paid_at DESC, created_at DESC`,
        [consignorId]
    );

    payoutsLogger.info("consignment.payouts.list.succeeded", {
        consignorId,
        count: rows.length,
    });

    return rows.map(mapPayoutRow);
}

export async function getTotalPaidForConsignor(consignorId) {
    const row = await db.queryOne(
        `SELECT COALESCE(SUM(amount), 0) AS total_paid
         FROM consignor_payouts
         WHERE consignor_id = $1`,
        [consignorId]
    );

    return Number(row?.total_paid || 0);
}

export async function createPayoutForConsignor(consignor, payload) {
    const receiptNumber = createReceiptNumber();
    const paidAt = payload.paidAt ? new Date(payload.paidAt) : new Date();

    if (Number.isNaN(paidAt.getTime())) {
        return { error: "invalid_paid_at", status: 400 };
    }

    const amount = Number(payload.amount || 0);

    if (!Number.isFinite(amount) || amount <= 0) {
        return { error: "invalid_amount", status: 400 };
    }

    const owedBefore = Number(payload.owedBefore || 0);
    const totalPaidBefore = Number(payload.totalPaidBefore || 0);
    const totalPaidAfter = totalPaidBefore + amount;
    const owedAfter = Math.max(0, owedBefore - amount);

    const receiptHtml = buildReceiptHtml({
        receiptNumber,
        displayName: consignor.display_name,
        email: consignor.email,
        paidAt: paidAt.toISOString(),
        paymentMethod: payload.paymentMethod,
        amount,
        note: payload.note,
        owedBefore,
        totalPaidAfter,
        owedAfter,
    });

    const rows = await db.query(
        `INSERT INTO consignor_payouts (
            consignor_id,
            amount,
            paid_at,
            payment_method,
            note,
            receipt_number,
            receipt_html
         )
         VALUES ($1, $2, $3, $4, $5, $6, $7)
         RETURNING id, amount, paid_at, payment_method, note, receipt_number, created_at`,
        [
            consignor.id,
            amount,
            paidAt.toISOString(),
            payload.paymentMethod || null,
            payload.note || null,
            receiptNumber,
            receiptHtml,
        ]
    );

    payoutsLogger.info("consignment.payouts.create.succeeded", {
        consignorId: consignor.id,
        payoutId: rows[0]?.id,
        amount,
    });

    return {
        payout: mapPayoutRow(rows[0]),
    };
}

export async function getReceiptHtmlForConsignor(consignorId, payoutId) {
    const row = await db.queryOne(
        `SELECT receipt_html
         FROM consignor_payouts
         WHERE consignor_id = $1 AND id = $2`,
        [consignorId, payoutId]
    );

    return row?.receipt_html || null;
}
